### ISSUE TITLE
Error with rotate_bound with Conda Install

### ISSUE THREAD

**Issue by btoderian** [freemocap/freemocap#105]
I've followed the conda style installation instructions, but I'm getting an error before the video files have been saved.  MP4 files are 1kb each.  Timestamps are recorded for 2224 frames or so. 
<img width="568" alt="2022-02-10 14_51_05-Cmder" src="https://user-images.githubusercontent.com/46722757/153511704-5a99bb83-0ae7-4727-85d8-474f6a9f6011.png">

**Comment by aaroncherian** [comment]
Congrats! you've found an error I've never seen before.

What seems to be happening is that it's trying to rotate a frame of the video, but it fails to detect the frame. So a few questions, so we can try and pinpoint what exactly is going on. 

What version of freemocap do you have installed?

The original videos you recorded should still be saved in your session folder, in a folder called RawVideos. do those work/play correctly?

Did you use any rotation options when you were recording?

And finally in that session folder, there should be a file called '[your session id]_config.yaml'. Would you mind attaching that file?

**Comment by btoderian** [comment]
Hi Aaron,

I used the conda style installation workflow, (actually using miniConda w conda v 4.10.3)  I configured the env to match the instructions, including python 3.7.11.  I'm using freemocap 0.0.48, and I used ipython v 7.31.1 in my shell to launch it.  

While I was able to initialize and setup the cameras, i have not been able to successfully save any data from them.  The files are initiated, but always result in a 1kb file.  The timestamps csv indicates i have 2224 frames where both cameras were sampled.

I saw an error about divx, so i switched to mp4v as the output suggested.  ive tried 60fps (which is what my cameras are rated to, but i noticed they are only capturing about 45fps.  I had the same resulting 1kb files in both cases.  i did not use any rotation features on this pass.

[sesh_2022-02-10_14_54_19_config.zip](https://github.com/jonmatthis/freemocap/files/8052654/sesh_2022-02-10_14_54_19_config.zip)

**Comment by aaroncherian** [comment]
Gotcha - so the codex and fps settings in the GUI right now need some work - in particular the fps setting doesn't affect the fps of the camera in any way it's more for the opencv video creation side. 

Just to confirm, the only things in the RawVideos folder are those 1kb files? 

Out of curiosity, what kind of cameras are you using?

**Comment by btoderian** [comment]
Thanks for having a look.  I made a few more attempts in the meantime, and had some success.   I think the main issue I had was that initially I had two different types of cameras, but simplifying to [a single type](https://www.amazon.com/gp/product/B08PYGJMCD) worked.  I was able to get through the rest of the pipeline (until I hit maya, LOL) 

Trying to add [this camera](https://www.amazon.com/gp/product/B0923ZRY2Z) did not work, and where I see that NoneType error and get the 1kb raw video files.

These cameras are rated for 60fps at 1080p, but I wasn't able to achieve that fps - the most I could get was 12fps.  I dropped the resolution to 720p in the gui and was able to get 30fps recorded.  I assumed it was due to capturing the higher resolution, but if the GUI doesn't affect the settings, then i'm not sure why I saw a performance difference between sessions, do you have any suggestions for ensuring a 60fps capture? 

Thanks!

**Comment by aaroncherian** [comment]
Ah yeah, so with the current version of the software, using a single type of webcam is the best way to go right now. The issue with that specific camera you bought not being able to save any recordings is a new one though, I don't think we've run into that issue yet.

Did you run into a Blender error similar to the one referenced in this issue? #104 

If that's the case, we've fixed that on the Github version of the code and it'll be pushed alongside the next update. 

As for the FPS issues - I should clarify that the FPS values on the GUI doesn't affect the performance. The resolution options on the GUI definitely do. Running higher resolution recordings with simultaneous webcams leads to frame drops, with the bottleneck possibly being with the computer/USB hub trying to intake all that data. Lowering the resolution will increase the capture framerate that you see. A 640x480p recording might get you closer to 60fps. 

I'm tagging @jonmatthis. He might have some thoughts here/fill in things that I missed.

**Comment by btoderian** [comment]
Ah! Makes sense re: the camera types and I'll probably stick to the successful camera moving forward (since it also has a wide-angle lens which helps me fit into frame) 

Thanks for the tips regarding frame rates.  Eventually I'd like to use 4 of these cameras, so I'll test different port combinations to try and get to 60fps with multiple streams.  When I use other apps, like windows 'Camera' app, I do get the framerates I expect reported, so they seem functional.

My blocker with Maya comes from a few maya specific issues - I'm using maya 2020 (which uses python 2.7) doesn't have pip by default, and has it's own version of numpy and scipy which complicates testing.  I'll probably switch to blender for plotting the data onto a skeleton and export that.  

Thanks very much - although the initial problem hasn't been resolved, I was able to move around the issue so you can update this ticket to reflect that if you like!

**Comment by danialldev** [comment]
> Ah yeah, so with the current version of the software, using a single type of webcam is the best way to go right now. The issue with that specific camera you bought not being able to save any recordings is a new one though, I don't think we've run into that issue yet.
> 
> Did you run into a Blender error similar to the one referenced in this issue? #104
> 
> If that's the case, we've fixed that on the Github version of the code and it'll be pushed alongside the next update.
> 
> As for the FPS issues - I should clarify that the FPS values on the GUI doesn't affect the performance. The resolution options on the GUI definitely do. Running higher resolution recordings with simultaneous webcams leads to frame drops, with the bottleneck possibly being with the computer/USB hub trying to intake all that data. Lowering the resolution will increase the capture framerate that you see. A 640x480p recording might get you closer to 60fps.
> 
> I'm tagging @jonmatthis. He might have some thoughts here/fill in things that I missed.

Hi, I'm intended to buy few webcams for 3d reconstruction, do 3 cameras provide good 3d output? is it better to use more cameras? what is your camera recommendation for better camera synchronization? @aaroncherian

**Comment by aaroncherian** [comment]
Sorry about the delayed response here:

So 3 is a good number of cameras. The minimum you need is 2, and we typically tend to use 4 in our recording sessions. Depending on how large the space you want to capture is, the more cameras you have at different angles of the person you're tracking, the more you can mitigate some of the limb occlusion issues that can happen with mediapipe. When I test out the code I usually use just 2 cameras and I've gotten fine data from that. But, the more cameras you add the more intense it is processing-wise to run them all at once. 

Camera-wise for better synchronization I'll note that we've only tested this with webcams that run up to 30fps max, we haven't tried on any 60fps cameras, so I can't actually tell you for certain whether reaching 60fps running webcams through the software is possible. The main issue here is that even if the camera is rated for 30 or 60fps the amount of data that you can squeeze through the USB port, especially when you're running multiple cameras, can lead to lower fps rates. The big factors that affect this in particular are the number of cameras you're running at once, the resolution that you're running them at, and the computer hardware. It's sort of a trade-offs situation, where you might have to sacrifice resolution for a higher framerate and that sort of thing. But I know you can get quite a few webcams at once running 30fps at a 720p resolution. Going above 720p always seems to cause issues. You can also try a 640x480 resolution and see where that gets you. 

For reference, we typically tend to use webcams that look like this: https://www.amazon.com/Streaming-Microphone-Widescreen-Conferencing-Recording/dp/B082X91MPP

Last thing I'll say is that if you're set on getting a solid 60fps, you can use videos recorded by external cameras (like a GoPro). All you need to do is be able to sync the videos together and trim them so they all have the same number of frames (we use Adobe Premiere's audio syncing and trimming functions), and you can feed those external videos through the pipeline as well.
