### ISSUE TITLE
Unreal Engine Integration

### ISSUE THREAD

**Issue by Jaegermeiste** [freemocap/freemocap#123]
Integration with Unreal would be a huge game changer! See

[https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/SkeletalMeshAnimation/LiveLinkPlugin/](https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/SkeletalMeshAnimation/LiveLinkPlugin/)

**Comment by jonmatthis** [comment]
Yeah, totally! We're definitely planning on integrating with Unreal at some point (hopefully soon!).

We're focusing on a refactor of the core software now, which will make it easier to build these kinds of integrations :)

**Comment by mdkberry** [comment]
any word on this? Even if it's an export out via Blender into UE5 to animate Metahumans would be cool.

**Comment by aaroncherian** [comment]
Hey there - while we haven't set up an integration pipeline into Unreal yet, one of our users actually has managed to do it. You can join our discord, and here's a link to their message: https://discord.com/channels/760487252379041812/881962838120349756/1124075954529128559

They wrote up some instructions and are working on automating a pipeline - and if you have questions you can try posting them in that channel and someone might be able to help you out!
