### ISSUE TITLE
Openpose License

### ISSUE THREAD

**Issue by Hunanbean** [freemocap/freemocap#130]
From what i understand, this relies on openpose. Last time i checked openpose is not freely available for commercial use. Can you clearly state or point to a license agreement that says we can use this commercially, before we invest a lot of time just to find out that, A. we cannot use it commercially, or B. it costs so much to use commercially, we are better off just buying a commercial system.

Thank you

**Comment by trentwirth** [comment]
FreeMoCap is currently set up to easily slot in OpenPose, among other ML body tracking Algorithms, like Google mediapipe. A lot of the visualizations you've seen rely on mediapipe, which uses an Apache 2.0 License (re: https://github.com/google/mediapipe/blob/master/LICENSE )

We are committed to continually slotting in the most powerful and permissible algorithms out there, as more continue to develop. As we see it, that's one of the strengths of FreeMoCap - we're not bound to a particular algorithm.

Let me know if you have any more questions about this, I'll answer them the best I can!

**Comment by Hunanbean** [comment]
Very informative, and good news!

Thank you very much
