### ISSUE TITLE
Charuco board print size

### ISSUE THREAD

**Issue by ecations** [freemocap/freemocap#142]
Hi!

Is there a certain size requirement for the printed charuco board? In your examples the size of the board is rather large and would require a large and expensive printer. Is a standard A4 print too small for this?

Thanks!

**Comment by and-rad** [comment]
If you're recording on a ktichen table or have a 4K camera, you might be lucky. Otherwise, A4 would simply be too small to be detected by the cameras even at a distance of 2 meters. I suggest finding a copy shop close to your home and letting them print it for you. It's just a couple bucks.
