### ISSUE TITLE
Ship a proper GUI

### ISSUE THREAD

**Issue by and-rad** [freemocap/freemocap#149]
The project is promising, but the setup is quite tedious. How are you feeling about developing a proper GUI that also bundles all of the dependencies? [PyQt](https://riverbankcomputing.com/software/pyqt/) would be an obvious choice, maybe a browser frontend would also work. I'm happy to help if you're interested.

**Comment by jonmatthis** [comment]
Yeah, for sure! We're currently working towards an "alpha" release writing the next few weeks/months. That'll have a proper front-end/back-end API design with a full GUI.

Plan is it start with a webapp and then transition to an Electron based stand-alone application.


I'm also kinda sorta thinking of building a pyqtgraph GUI to maintain a "pure python" version, and a Textual based terminal interface for a GUI-free version


All in good time 😊
