### ISSUE TITLE
Output to csv (via `pandas.dataframe`)

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#155]
Reformat data in - `[freemocap_data_folder]/[session_folder]/DataArrays/mediaPipeSkel_3d_smoothed.npy` into a `pandas.DataFrame` and then save to `.csv`

That `npy` file will load a numpy array (name it something like- `mediapipe3d_numFrames_numTrackedPoints_XYZ` with the following dimensions:

```
# dimension (mediapipe3d_numFrames_numTrackedPoints_XYZ.shape) :
0 - number_of_frames_in_the_synchronized_videos
1 - numer_of_tracked_points
2 - Spatial dimension, 0=x, 1=y, 2=z
```

Columns should include the `X`, `Y`, `Z` values, with rows denoting `frame_number`

The final size should be:

```
num_columns = number_of_trackedPoints * 4
num_rows = number_of_frames_in_synchronized_videos #not counting the header
```

Hints - 

1 - You might find it difficult to put 3D data into a 2d DataFrame. The project `xarrays` was created to help with that. It might be easier to go:  `numpy` -> `xarray` -> `pandas` -> `.csv`

2 - For bonus points, put `reprojection_error` in there too. You can find that in the `DataArrays` folder, with similar structure to the `XYZ` data

Notes:
Blocks - #170

**Comment by MocapMike** [comment]
Able to convert NumPy to pandas df successfully (meaning something comes out without a shaping error). 

Now in the process of verifying if the shape is correct and parsing out the body, face, and hands. 

Exporting to .csv is straightforward involving one line of code. 

^^^ will update this comment with more specifics i.e. including code.
