### ISSUE TITLE
Clean up references to Session throughout the Codebase

### ISSUE THREAD

**Issue by endurance** [freemocap/freemocap#182]
Many Classes downstream of the entrypoints have knowledge of sessions, when they should only have knowledge of themselves and what they need to function.

This ticket is to capture all of the work necessary to clean that up.

**Comment by jonmatthis** [comment]
The existing GUI pipeline was cobbled together from various older methods, and often relies on knowing the `session_id` so methods can load in data from that session folder. 

We should clean this up by removing the dependency on `session_id` and just feed each method *only* the data they need to do the task that needs doing

clean up this slop in the main GUI workflow - 

- [ ] `ShowCamsCharuco._run_anipose_calibration` relies on old `CalibrationPipelineOrchestrator.run_anipose_calibration()` method
- [ ] `RecordVideos._detect_2d_skeletons` relies on old `MediaPipeSkeletonDetector.process_session_folder()` method
- [ ] `RecordVideos._detect_3d_skeletons` relies on old `SessionPipelineOrchestrator()` method
- [ ] `RecordVideos._create_blender_scene_from_session_data` relies `session_id`
