### ISSUE TITLE
Can't use multiple cameras on Ubuntu 20.04

### ISSUE THREAD

**Issue by frnsys** [freemocap/freemocap#216]
Hi, thanks for all your work on this project. I'm excited to see where it goes.

I'm having an issue where I can't seem to get this working with multiple cameras. I have three webcams plugged directly into my laptop (I also tried plugging into a hub, but didn't change anything).

When I go through the camera setup process and click "Submit", only the first camera lights up and only a blank rectangular window appears. 

This is the output I see:

```
__________________________________________
cv2::videocapture properties for Camera# 0
CV_CAP_PROP_FRAME_WIDTH: '640.0'
CV_CAP_PROP_FRAME_HEIGHT : '480.0'
CAP_PROP_FPS : '30.0'
CAP_PROP_EXPOSURE : '0.008200820082008202'
CAP_PROP_POS_MSEC : '0.0'
CAP_PROP_FRAME_COUNT  : '-1.0'
CAP_PROP_BRIGHTNESS : '0.5019607843137255'
CAP_PROP_CONTRAST : '0.12549019607843137'
CAP_PROP_SATURATION : '0.12549019607843137'
CAP_PROP_HUE : '-1.0'
CAP_PROP_GAIN  : '0.20392156862745098'
CAP_PROP_CONVERT_RGB : '1.0'
__________________________________________
```

It looks like it's getting stuck on the first camera and never manages to start up the other cameras?

It works fine if I select just one camera.

**Comment by frnsys** [comment]
I looked into this and the camera setup/recording threads were blocking each other. I switched to using multiprocessing instead and that seems to work.

I had to make a few other small changes to get things working; they're all in this commit: https://github.com/frnsys/freemocap/commit/3036555124feac4c53cc2aff3a11bfd6304c37fe

I realize though those changes might not be relevant as you're refactoring the code anyways, but hopefully it's helpful to someone :)

**Comment by HitLyn** [comment]
Many thanks for sharing the solution. I have the same problem here. Why not create a pull request? I guess this should be a common problem for all ubuntu 20.04 users.

**Comment by jonmatthis** [comment]
Great thought, but not the right time :) 

We've frozen development on the `pre-alpha` version of the code at [`v0.0.54`](https://github.com/freemocap/freemocap/releases/tag/v0.0.54), so we aren't in a position to incorporate the PR

We're getting UNBEARABLY CLOSE to release of the new `alpha` version of this software which will include a full GUI based controller will be cross-platform compatible. 

Thanks for the interest and the work! Stay tuned :D

**Comment by HitLyn** [comment]
> 

Exciting to hear about that! Thanks for your contribution to the community. I have already recommended your work to my colleagues.

**Comment by HitLyn** [comment]
> Great thought, but not the right time :)
> 
> We've frozen development on the `pre-alpha` version of the code at [`v0.0.54`](https://github.com/freemocap/freemocap/releases/tag/v0.0.54), so we aren't in a position to incorporate the PR
> 
> We're getting UNBEARABLY CLOSE to release of the new `alpha` version of this software which will include a full GUI based controller will be cross-platform compatible.
> 
> Thanks for the interest and the work! Stay tuned :D

Exciting to hear about that! Thanks for your contribution to the community. I have already recommended your work to my colleagues.
