### ISSUE TITLE
FreeMoCap output processing

### ISSUE THREAD

**Issue by BeNavon** [freemocap/freemocap#218]
Hi,

I am a mechanical engineering student using freemocap as part of a mini-project, thank you so much for this software. I made an attempt to record a short session, but now am not entirely sure how to process the data of the session. For example, is there a way to translate the movement in the video to an Excel file which shows data like angle between joints?
Are there any tutorials or further information that can assist me in processing the software information?

Thank you again.

**Comment by jonmatthis** [comment]
Hello!

We don't have much by way of tutorials just yet - that's high on the priority list for the next couple of months.

In the meantime, I recently put together this ipython jupyter notebook to convert the `numpy` array that gets placed into the `DataArrays` folder into:

- individual numpy arrays for the body, hands, and face, and
- `pandas.DataFrame` derived `csv` files with labeled columns

You can find it here - https://github.com/freemocap/freemocap/blob/jon/npy_to_csv_ipynb/ipython_jupyter_notebooks/export_freemocap_npy_as_pandas_data_frame_csv.ipynb

Let me know if that's helpful! If you have anything specific in mind that you're trying to do, I'd recommend joining the Discord server and asking questions(and sharing progress) there - https://discord.gg/2Kca6zzJ

cheers
Jon
