### ISSUE TITLE
Using Blender from Wrong Session

### ISSUE THREAD

**Issue by DestroytheCity** [freemocap/freemocap#241]
I started a new FMC session, yet when running Stage 5 FMC keeps using the .blend from my original project instead of the new one i made for it in the right session folder. It then fails saying that the file doesn't exist. Any thoughts?  *replaced login with X 

Running sesh 2 from /home/X/bac_mj_ar/FreeMocap_Data
────────────────────────────────────────────────────────────────────────────────
Using blender executable located at: /home/X/bac_mj_ar/FreeMocap_Data/sesh/Session_ID.blend
Skipping Video Recording
Skipping Video Syncing
Skipping Calibration
Skipping 2d point tracking
────────────────────────────────────────────────────────────────────────────────
────────────────────────────── EXPORTING FILES... ──────────────────────────────
─ Hijacking Blender's file format converters to export FreeMoCap data as vari… ─
────────────────────────────────────────────────────────────────────────────────
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/X/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemoca │
│ p/fmc_runme.py:335 in RunMe                                                  │
│                                                                              │
│   332 │   │   │   │   │   │   │   │   │   │   command_str,                   │
│   333 │   │   │   │   │   │   │   │   │   │   shell=False,                   │
│   334 │   │   │   │   │   │   │   │   │   │   stdout=subprocess.PIPE,        │
│ ❱ 335 │   │   │   │   │   │   │   │   │   │   stderr=subprocess.PIPE         │
│   336 │   │   │   │   │   │   │   │   │   │   )                              │
│   337 │   │   │   │   while True:                                            │
│   338 │   │   │   │   │   output = blender_process.stdout.readline()         │
│                                                                              │
│ /home/X/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:800 in   │
│ __init__                                                                     │
│                                                                              │
│    797 │   │   │   │   │   │   │   │   p2cread, p2cwrite,                    │
│    798 │   │   │   │   │   │   │   │   c2pread, c2pwrite,                    │
│    799 │   │   │   │   │   │   │   │   errread, errwrite,                    │
│ ❱  800 │   │   │   │   │   │   │   │   restore_signals, start_new_session)   │
│    801 │   │   except:                                                       │
│    802 │   │   │   # Cleanup if the child failed starting.                   │
│    803 │   │   │   for f in filter(None, (self.stdin, self.stdout, self.stde │
│                                                                              │
│ /home/X/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:1551 in  │
│ _execute_child                                                               │
│                                                                              │
│   1548 │   │   │   │   │   │   err_msg = os.strerror(errno_num)              │
│   1549 │   │   │   │   │   │   if errno_num == errno.ENOENT:                 │
│   1550 │   │   │   │   │   │   │   err_msg += ': ' + repr(err_filename)      │
│ ❱ 1551 │   │   │   │   │   raise child_exception_type(errno_num, err_msg, er │
│   1552 │   │   │   │   raise child_exception_type(err_msg)                   │
│   1553                                                                       │
│   1554                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 
'/home/X/bac_mj_ar/FreeMocap_Data/sesh/Session_ID.blend --background 
--python /home/X/.conda/envs/freemocap-env/lib/python3.7/site-packages/fre
emocap/freemocap_blender_megascript.py -- 
/home/X/bac_mj_ar/FreeMocap_Data/sesh 2 0': 
'/home/X/bac_mj_ar/FreeMocap_Data/sesh/Session_ID.blend --background 
--python /home/X/.conda/envs/freemocap-env/lib/python3.7/site-packages/fre
emocap/freemocap_blender_megascript.py -- 
/home/X/bac_mj_ar/FreeMocap_Data/sesh 2 0'

**Comment by jonmatthis** [comment]
It's probably saying that it can't find the `blender.exe` executable to create a NEW `.blend` file for your current session!

Try re-running with the `resetBlenderExe` flag set to `True` in the `RunMe` call - It should pop up a little helper GUI where you can navigate to the location of a `blender.exe` exectuable on your computer (The software will use that to run the `freemocap_blender_megascript.py` file to create a `blend` from your current data. )

A standard install of Blender from https://blender.org will put the `.exe` in this location on your computer: 

`C:\Program Files\Blender Foundation\Blender 3.2\blender.exe`

let me know if it works!

**Comment by jonmatthis** [comment]
no no - You need to select the location of **blender executable**, not a `.blend` file. The file will be named `blender.exe` and will located in a place like - 

`C:\Program Files\Blender Foundation\Blender 3.2\blender.exe`

...after installing Blender from https://blender.org

**Comment by DestroytheCity** [comment]
The same error remains; not sure why it is looking for "sesh 2 0" as a location. 

───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemoca │
│ p/fmc_runme.py:335 in RunMe                                                  │
│                                                                              │
│   332 │   │   │   │   │   │   │   │   │   │   command_str,                   │
│   333 │   │   │   │   │   │   │   │   │   │   shell=False,                   │
│   334 │   │   │   │   │   │   │   │   │   │   stdout=subprocess.PIPE,        │
│ ❱ 335 │   │   │   │   │   │   │   │   │   │   stderr=subprocess.PIPE         │
│   336 │   │   │   │   │   │   │   │   │   │   )                              │
│   337 │   │   │   │   while True:                                            │
│   338 │   │   │   │   │   output = blender_process.stdout.readline()         │
│                                                                              │
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:800 in   │
│ __init__                                                                     │
│                                                                              │
│    797 │   │   │   │   │   │   │   │   p2cread, p2cwrite,                    │
│    798 │   │   │   │   │   │   │   │   c2pread, c2pwrite,                    │
│    799 │   │   │   │   │   │   │   │   errread, errwrite,                    │
│ ❱  800 │   │   │   │   │   │   │   │   restore_signals, start_new_session)   │
│    801 │   │   except:                                                       │
│    802 │   │   │   # Cleanup if the child failed starting.                   │
│    803 │   │   │   for f in filter(None, (self.stdin, self.stdout, self.stde │
│                                                                              │
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:1551 in  │
│ _execute_child                                                               │
│                                                                              │
│   1548 │   │   │   │   │   │   err_msg = os.strerror(errno_num)              │
│   1549 │   │   │   │   │   │   if errno_num == errno.ENOENT:                 │
│   1550 │   │   │   │   │   │   │   err_msg += ': ' + repr(err_filename)      │
│ ❱ 1551 │   │   │   │   │   raise child_exception_type(errno_num, err_msg, er │
│   1552 │   │   │   │   raise child_exception_type(err_msg)                   │
│   1553                                                                       │
│   1554                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 
'/home/x/blender/blender-3.2.0-linux-x64/blender --background --python /ho
me/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/freem
ocap_blender_megascript.py -- /home/x/bac_mj_ar/FreeMocap_Data/sesh 2 0': 
'/home/x/blender/blender-3.2.0-linux-x64/blender --background --python /ho
me/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/freem
ocap_blender_megascript.py -- /home/x/bac_mj_ar/FreeMocap_Data/sesh 2 0'

**Comment by jonmatthis** [comment]
hmm - Might be you to reset your `freemocap_data_path` - Try setting  `setDataPath==True` in the `RunMe` and select your `FreeMoCap_Data` folder (apparently located at `/home/x/bac_mj_ar/FreeMocap_Data` for you) 

If that doesn't work, please post the exact command you're using to launch the session (i.e. the `freemocap.RunMe(....)` part)

**Comment by DestroytheCity** [comment]
Error remains...command is 
freemocap.RunMe(sessionID="sesh 2",stage=5,debug=True,setDataPath=True,userDataPath=True,charucoSquareSize=68,calVideoFrameLength=0.80,useBlender=True)

Prior steps were run yesterday

**Comment by jonmatthis** [comment]
Ohhh - I bet its not happy that you put a `space` in your session title! 

The blender command is run through subprocess, so I think it can't handle whitespace in paths.... 


If you really want to process the videos in the `sesh 2` folder, you can brute-force a fix by:

1.  start a new session (keep the default session name)
2, Record some simple videos (nothing fancy, just enough to make the software create the session folder. Don't worry about th enumber of cameras or showing the charuco board)
3. Follow the process past the time stamp line plots (it'll fail in the 'stage=3, calibration' part)
4. Kill the program, navigate to the new session folder
5. replace the 'RawVideos' and 'SynchedVideos' folders with the ones from the `sesh 2` folder 
6. re-run the process pointing at the NEW session folder, starting at `stage=3`

Alternatively - Don't bother with any of that and just record a new session without spaces in the name :P

**Comment by DestroytheCity** [comment]
Wow...sometimes the answer to a convoluted problem is the most straightforward component...

Rerunning stage 2 with a new file name first yields still yields the error code<;

Traceback (most recent call last):
  File "/home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c9d93b9226e8>", line 1, in <module>
    runfile('/home/x/.config/JetBrains/PyCharm2021.3/scratches/scratch.py', wdir='/home/x/.config/JetBrains/PyCharm2021.3/scratches')
  File "/home/x/pycharm-2021.3.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/x/pycharm-2021.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/x/.config/JetBrains/PyCharm2021.3/scratches/scratch.py", line 3, in <module>
    freemocap.RunMe(sessionID="test",stage=2,debug=True,setDataPath=True,userDataPath=True,charucoSquareSize=68,calVideoFrameLength=0.80,useBlender=True)
  File "/home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/fmc_runme.py", line 141, in RunMe
    timesync.time_sync_initialize(sesh)
  File "/home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/webcam/timesync.py", line 265, in time_sync_initialize
    session.initialize(stage = 2)
  File "/home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/session.py", line 217, in initialize
    raise ValueError('The number of frames in each video are not equal. Frame counts per video are are: ' + str(frames_per_cam))
ValueError: The number of frames in each video are not equal. Frame counts per video are are: {}

then the same error code as the comment above. was able to work originally with the same video input

**Comment by aaroncherian** [comment]
yeah - quick question - what exactly is your session name, and what is the name of any one of the synced videos in the SyncedVideos folder? (there's some naming conventions that have to match)

**Comment by jonmatthis** [comment]
No no - just run `freemocap.RunMe()` to create a new session, then do the stuff to swap out the videos 

(Again - only do this if you REALLY want to see the outcome of the `sesh 2` videos. Otherwise, just them off as a failed run and record new videos)

**Comment by aaroncherian** [comment]
a note re: step 4 - you can't just copy the SyncedVideos folder from the previous session into a new one - the video names are all tagged with a session ID. 

If your session ID = `session_x`, the SyncedVideos are all named something like `session_x_synced_cam_1` or something. If you want to move that SyncedVideos folder from `session_x` to `session_y`, you need to rename all the videos from `session_x_synced_cam_1` to `session_y_synced_cam_1`. The code looks for the session tag, so  if they don't match it won't find any videos in the synced videos folder, which could potentially lead to that error that you saw

also an alternative, potentially simpler solution than creating a new session and running it would be: 
1) create a new folder in your `FreeMocap Data` folder, give it whatever session ID you'd like
2) copy the SyncedVideos folder into that folder, and change the names of the videos in there based on the instructions above
3) do then do `freemocap.RunMe(sessionID = 'insert_your_new_id_here', stage =3)`

**Comment by DestroytheCity** [comment]
Followed the instructions and created a new project. The error remains: 

────────────────────────────── EXPORTING FILES... ──────────────────────────────
─ Hijacking Blender's file format converters to export FreeMoCap data as vari… ─
────────────────────────────────────────────────────────────────────────────────
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemoca │
│ p/fmc_runme.py:335 in RunMe                                                  │
│                                                                              │
│   332 │   │   │   │   │   │   │   │   │   │   command_str,                   │
│   333 │   │   │   │   │   │   │   │   │   │   shell=False,                   │
│   334 │   │   │   │   │   │   │   │   │   │   stdout=subprocess.PIPE,        │
│ ❱ 335 │   │   │   │   │   │   │   │   │   │   stderr=subprocess.PIPE         │
│   336 │   │   │   │   │   │   │   │   │   │   )                              │
│   337 │   │   │   │   while True:                                            │
│   338 │   │   │   │   │   output = blender_process.stdout.readline()         │
│                                                                              │
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:800 in   │
│ __init__                                                                     │
│                                                                              │
│    797 │   │   │   │   │   │   │   │   p2cread, p2cwrite,                    │
│    798 │   │   │   │   │   │   │   │   c2pread, c2pwrite,                    │
│    799 │   │   │   │   │   │   │   │   errread, errwrite,                    │
│ ❱  800 │   │   │   │   │   │   │   │   restore_signals, start_new_session)   │
│    801 │   │   except:                                                       │
│    802 │   │   │   # Cleanup if the child failed starting.                   │
│    803 │   │   │   for f in filter(None, (self.stdin, self.stdout, self.stde │
│                                                                              │
│ /home/x/.conda/envs/freemocap-env/lib/python3.7/subprocess.py:1551 in  │
│ _execute_child                                                               │
│                                                                              │
│   1548 │   │   │   │   │   │   err_msg = os.strerror(errno_num)              │
│   1549 │   │   │   │   │   │   if errno_num == errno.ENOENT:                 │
│   1550 │   │   │   │   │   │   │   err_msg += ': ' + repr(err_filename)      │
│ ❱ 1551 │   │   │   │   │   raise child_exception_type(errno_num, err_msg, er │
│   1552 │   │   │   │   raise child_exception_type(err_msg)                   │
│   1553                                                                       │
│   1554                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 
'/home/x/blender/blender-3.2.0-linux-x64/blender --background --python /ho
me/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/freem
ocap_blender_megascript.py -- /home/x/bac_mj_ar/FreeMocap_Data/test 0': 
'/home/x/blender/blender-3.2.0-linux-x64/blender --background --python /ho
me/x/.conda/envs/freemocap-env/lib/python3.7/site-packages/freemocap/freem
ocap_blender_megascript.py -- /home/x/bac_mj_ar/FreeMocap_Data/test 0'

**Comment by jonmatthis** [comment]
Oh wait - You're on linux!

We don't officially support linux yet, but if you are able to get things working that's great! 

You won't have a `blender.exe` to point the Blender output stage towards, but you can try doing that for the linux equivalent to see if that works. 

Alternatively, if you open the `freemocap_blender_megascript.py` file in the Scripting tab of Blender, change the path to point towards your session folder, and run that - it should work to create a `blend` file. 

And don't put spaces in your session id!

Versions after `0.1.0` will have better cross platform support. Follow along in the Discord for updates, and thanks for the interest :)
