### ISSUE TITLE
freemocap-gui (alpha): fails to detect camera #2, but otherwise works (bravo!)

### ISSUE THREAD

**Issue by mjhmilla** [freemocap/freemocap#250]
The alpha-version of freemocap-gui detects:

- camera 0 (built in laptop camera)
- camera 1 (attached USB web camera)

but fails to detect

- camera 2 (attached USB web camera)

The two web cameras are directly connected to the laptop (not through a hub) and are other wise identical. That said, otherwise the freemocap-gui appears to work: using cameras 0 and 1 I was able to calibrate the cameras, record, run the pose estimation and triangulation, and view the output in blender.

Bravo!

**Comment by jonmatthis** [comment]
Awesome! Glad you were able get it working! That's great!!

Regarding your cameras:

 - Have you tried swapping the cameras between the different USB ports? 
 - Are you able to disable your laptop camera and re-run the detection?

I want to differentiate between:

1. Is it a problem with one of your cameras?
2. Is it a problem with one of your USB ports? 
3. Is it a  problem with the number of cameras (i.e. the software + your computer can only handle 2 cameras total)? 

Thanks again for your interest in the project (and your well-written and researched Issues :D) !

**Comment by mjhmilla** [comment]
Dear @jonmatthis,

Disabling the internal camera fixed the problem. Thank you for the suggestion - it's so exciting to see everything working : )

Yours,

@mjhmilla
