### ISSUE TITLE
Using external videos

### ISSUE THREAD

**Issue by abhisuri97** [freemocap/freemocap#255]
Is there any way to use external video sources with FreeMoCap? I currently have a set of 8 camera angles that I cannot access directly via USB (they're saved to a hard drive and are available to me after processing in the form of 8 different mp4 files). 

Also, as part of the pre-processing, we know that all of the videos are synced to the exact same # of frames.

**Comment by aaroncherian** [comment]
Hey, yeah - with the pre-alpha code you currently can, though there's some manual effort involved. With the alpha code you'll be able to soon. 

If you'd like to do it with the pre-alpha code, I wrote up this response for another user, so hopefully that's helpful:

You can use cameras that aren't connected to the computer (we've recorded with GoPro's). The only catch is that those external videos need to be synced and they all need to have the exact same number of frames. There's a variety of ways to sync videos, we tend to use audio syncing in a video editing program to do it, but that's essential to getting a good reconstruction.

There's also a good bit of manual setup on the user end to get the videos to run through code - this should get smoothed over in future work, but for now there are a few steps to go through.

1) When you have your videos, create a FreeMocap_Data folder, if you don't have one made already. 
2) Inside that folder, create a folder for your session. The name of that folder is the session ID, you can call it whatever you want (e.g. session_test)
3) Inside your session folder, create a folder called SyncedVideos
4) Copy your videos into the SyncedVideos folder. 
5) Rename each video in this format: [insert_session_id_here]_synced_Cam1]
using the example session ID name I'd mentioned in step 2 - if we had 2 videos they would be named session_test_synced_Cam1 and session_test_synced_Cam2
6) Now when you run FreeMoCap, run the code using the sessionID = [insert_session_id_here] and  stage = 3 flags in the RunMe command. You may need to add the setDataPath = True command in there too. This will bring up a GUI that you can use to point to where your FreeMocap_Data folder is. Again just as an example, your RunMe command might look something like RunMe(sessionID = 'session_test', stage = 3, setDataPath = True)

and then it should start processing your videos

**Comment by abhisuri97** [comment]
Awesome. thank you. Additional question, for the calibration Charuco square would you recommend that it be static in the background (e.g. taped to a wall) or should we try and move it around during calibration?
