### ISSUE TITLE
Multi Camera Calibration Failure

### ISSUE THREAD

**Issue by DestroytheCity** [freemocap/freemocap#258]
My team and I are attempting to use FreeMoCap for a system that records eight views in synchrony. We are currently having issues calibrating all eight cameras, which face opposing directions in our hallway set-up, making it difficult for them to see one CharUco board at once. To resolve this, we printed a double-sided CharUco board, allowing us to create a 3D skeleton output; however, the skeleton seems to be both inverted and translated compared to the subject from certain camera angles. We then tried to calibrate our system using hallway cameras on one side, which all face each other and can observe a charUco board simultaneously. Still, we saw the output skeleton as translated and inverted, ruling out the double-sided board as the reason for the translation. Any suggestions on how to calibrate a system set up like this or why the skeletons seem to be inverted/displaced?

Attached is a link with the videos and data array/calibration files for the 8 camera set-up.
https://drive.google.com/drive/folders/1wv4RHzPFDLeIXr9xONC72fhbW3MKQT_q?usp=sharing

**Comment by aaroncherian** [comment]
Hey there. This is a new one for me! 

First question, did you record these using webcams that ran through FreeMoCap, or are these videos from an external source (like GoPro's)?

Also I'll make a note that not all of the cameras need to see the Charuco board at one single moment. At any moment you want multiple cameras to have a view of the board at once - but it doesn't have to be *all* the cameras. For example, if you had the cameras set up in a circle, you could stand in the center and rotate around in a circle and the calibration should still work fine.

**Comment by DestroytheCity** [comment]
Hey, thank you for the response! We recorded them externally using our camera set-up. 

In regards to your second point, does each camera need to see the board at the same time as all the other cameras at some point? For example, camera 1 needs to see the board at the same time as cameras 2-7 at some point during the calibration video, but 1-8 do not necessarily need to see the cameras at the same time throughout the entire video.

**Comment by aaroncherian** [comment]
Awesome - so I noticed in the animation that the videos were rotated either 90 or 270 degrees - so my first recommendation would be to orient the videos so that the person is standing upright and then feed those videos through the pipeline, and how it looks from there. 

In terms of the calibration - we use the calibration methods from a Python package called Anipose - which has this whole algorithm where it uses data from pairs of cameras seeing the board at once to reconstruct their positions. Here's a diagram from their paper, if you're interested in looking into it more (https://www.biorxiv.org/content/10.1101/2020.05.26.117325v1.full) : 
![image](https://user-images.githubusercontent.com/17153275/195908060-bc6dbf6d-fcb3-45c9-8ae6-1a7a934d9b3e.png)

From my experience, it's fine if say camera 1 doesn't see the board at the same time as every other camera during the calibration video. That being said, I'm not completely certain as to how a double-sided charuco board would affect the algorithm, and whether it would be helpful or if it would screw it up.

**Comment by DestroytheCity** [comment]
Sorry, could you clarify what you mean by orienting the videos so the person is standing upright? We have been inputting the videos so that the subject is standing upright and each video is in the same orientation. For context, our system records from all 8 cameras simultaneously, so we bypass stages 1 and 2 and run the system from stage 3. The same error arose when starting with stage 2 in our initial runs. 

I see what you mean regarding the calibration. I will try a single-sided calibration video with all 8 cameras over the weekend. I originally thought that it was the double-sided board causing this issue as the skeleton seems to be translated and inverted. Since the video still failed with a single-sided CharUco board when facing all cameras simultaneously (the half hallway, four-camera video), I want to say that there is something else throwing an error.

**Comment by aaroncherian** [comment]
Sure! So I noticed that in the output animation, the videos looked like this, where they were rotated on their sides.
![image](https://user-images.githubusercontent.com/17153275/195921413-5d411ee7-58ea-46f0-b87e-231cdd22adca.png)

Were the input videos rotated like that?

**Comment by DestroytheCity** [comment]
No, the input videos were all in the same orientation with the patient facing upright.

**Comment by aaroncherian** [comment]
Interesting - would it be possible for you to link me to a folder with some of the original videos in it?

**Comment by DestroytheCity** [comment]
Ah, I was wrong — the uploaded videos are rotated. I will orient them correctly and try calibration again with both the double and single-sided CharUco boards then report back. Thank you for the advice

**Comment by DestroytheCity** [comment]
So after flipping the videos to an upright orientation, they seem to be displaced still. I uploaded the folder with the data arrays, output, and original videos in the drive shared in this thread. Note, the name of the folder is sesh(noninverted), but when running it the name actually was just sesh.

**Comment by DestroytheCity** [comment]
After re-running with correctly oriented videos,  the calibration failed. As the same videos, just oriented standing upright, I'm not sure why this would have occurred. I've placed the synced videos into the Google Drive link shared above (synced videos).

I've also shared a calibration videos recorded w/a single sided CharUco board. Thank you so much for your help with this process.

**Comment by mprib** [comment]
@DestroytheCity, I'm curious how you went about the double-sided charuco creation as this is something I've had in the back of my mind as well. 

This may not be relevant to your issues but I thought I might put something here to document a consideration for "double-sided boards."

The charuco corners are uniquely identified within OpenCV (which Anipose is leveraging, I believe). I've attached an image that shows the corners (which each have specific number IDs). Just as an example, by holding the paper board differently, I occlude specific corners from being recognized. During the 3D reconstruction, the number of each corner on each 2D image is being used to identify the same point in space as seen by each camera. A mirror image of a board will make different Arucos which won't be recognized. But just printing the same board on each side will mean that there are now conflicting pieces of information being fed in. Corner 0 on one side will be corner 3 on the other side (For my board with 3 corners per row), which will create a strange situation for the OpenCV calibration to sort out. At least this is my understanding of the situation.

![charuco_corners](https://user-images.githubusercontent.com/31831778/196053098-fbd259c7-7f17-40a2-989c-65a3d8487c6d.png) _same camera but at two different times...aruco corners are highly specific and numbered_

Apologies if this is distracting side information or something you are already aware of. The calibration process is something I continue to obsess over and want to contribute something to make more bullet-proof.

**Comment by jonmatthis** [comment]
Hello - Thanks for the interest! 

It looks like you're using a `charuco_board` that is not the standard one we use in this project: 

![image](https://user-images.githubusercontent.com/15314521/196169496-0dc27b01-9b56-41f5-aaec-09f0a672d8f3.png)

(notice how your board has more squares in it than the standard board, found here - https://raw.githubusercontent.com/freemocap/freemocap/main/assets/charuco/charuco_board_image_highRes.png

.... I was about to give you instructions on how to alter our source code to fit your board defintion, but I just noticed that your board was defined so that it doesn't have black squares in all four corners (i.e. you defined it with an even numbers of rows or columns)! Sorry, but that means you won't be able to calibrate with that board. You'll have to print a new one (using our standard board definition :(

**Comment by jonmatthis** [comment]
If it was difficult or expensive for you to get that board printed, you could try altering it to fit the needs of the calibration code by covering up the bottom row of `aruco` squares with white paper and then altering the code to match the new definition (i.e. the board parameters that would produce a board without that last row, and with a black squares in all corners)

To alter the code to change the the charuco board definition- 

1. Find the location of your freemocap conda environment  (Open a conda enabled terminal and type `conda info -e`)

2. open the file at `[path_to_the_conda_environment]/Lib/site-packages/freemocap/fmc_runme.py` in some kind of text editor or IDE (e.g. VS Code)

3. Change the board definition on `Lines 126-133` to match your board definition (e.g. change the `7` and `5` to match your board's definition

**Comment by DestroytheCity** [comment]
Thank you for your responses! We will go ahead and print out a new board.

The idea for using a double sided board was that by using a mirrored image, it would be the same as if I physically turned around to face the other half of the cameras during calibration, but would allow for the board to be detected by most if not all cameras in all frames. We are also considered inverting one side of the board such that top right would be top right in both orientations, but felt like this may throw some issues with OpenCV. 

In your opinion, would it be most beneficial to reprint the same board with it mirrored on the other side (as we did for this test), invert it, or simply use a single sided board? Our calibration attempts with a single sided board all ultimately failed (see video in the google drive), even when using a standard CharUco board (the one that @jonmatthis linked). The error was: Could not build calibration graph. Some group of cameras could not be paired by simultaneous calibration
board detections. Check which cameras have different group numbers below to see the missing
edges. {0: 5, 1: 5, 2: 6, 3: 6, 4: 5, 5: 5, 6: 6, 7: 6}

When reprinting boards, what size checker square is recommended? We have been using a 24x36 sized board, and with less squares I assume the size of each CharUco board should be increased such that it fits the dimensions of the board. We are using the https://calib.io pattern generator. 

Again, many thanks for all the insight and helpful feedback.

**Comment by mprib** [comment]
> In your opinion, would it be most beneficial to reprint the same board with it mirrored on the other side (as we did for this test), invert it, or simply use a single sided board?

My personal suggestion would be to stick with a single sided board. I believe that it is possible to write code such that a double sided board can be tracked by cameras on opposite sides of a room for a single calibration but they would actually need to be two _different_ boards and special adjustments would have to be made to combine all the image points before it goes into the OpenCV calibration functions. I'm fairly confident that this functionality is not embedded in Anipose.

If it were two sides with the same board, then you run into the issue of corner 0 being at one point in space on side A,  then on side B that same point in space is recorded as corner 2 (using a 4 column board that has 3 corners per row as an example).

Regarding mirror images, I just double checked that they will not be picked up by opencv (aruco markers, the little square designs in the Charuco board, are not symmetircal):

![mirror_charuco](https://user-images.githubusercontent.com/31831778/196282212-b0f3fdfa-c850-4772-8aa9-1ad7f6abe663.png)

So the plain one-board solution seems the way to go in my mind. Regarding size: larger can improve visability, and there is a place to make this adjustment in the alpha gui version (I don't recall about the older pre-alpha).  The size will determine the scale of the reconstruction so if you can correct the scale later (or primarily just care about relative position) it may not be that big of a deal to you.

**Comment by DestroytheCity** [comment]
Thank you so much for your insights and explanations. 

To clarify, the square size can be 'anything,' as long as the code is updated to reflect that. We have printed out the standard CharUco board that @jonmatthis mentioned that is around 8.5x11. Would printing out a larger board (24x36 and increasing each checker width to around 100mm (see picture) be a wise idea and are there any other changes we would need to make beyond adjusting the square size in the code? 

<img width="1338" alt="Screen Shot 2022-10-17 at 2 30 54 PM" src="https://user-images.githubusercontent.com/114196168/196289571-3c244a29-45de-48c3-990e-d84248e06305.png">

**Comment by mprib** [comment]
>Also, is there a reason that you can think of that the single sided calibration (see google drive) was failing?

I think the issue is that the "top" bank of cameras have no way of understanding their relationship with the "bottom" bank of cameras. I believe that Anipose works best when there is a kind of "theatre in the round" setup with many cameras where all adjacent cameras can share a glimpse of the same board at the same time. If you weren't constrained to a hallway, I would suggest temporary 'bridge' cameras that will be able to share a view of the board as it rotates through the various fields of views. 

So it would be like Cam0 -->Cam1 --> Cam2-->Cama3-->Cam4-->temp bridge cameras........ --> Cam5 -->Cam6....

For two cameras to know where they are relative to each other, they have to see the same corners from the same board at the same time. You tell OpenCV what the objective reality of the board layout is. and the cameras figure out where they are relative to each other.

The opposing camera view setup will one day off an incredibly robust system for markerless motion capture, but sadly we aren't quite there yet. The challenges you are facing are at the heart of challenges that I want to address. We are working on it!

**Comment by DestroytheCity** [comment]
That makes total sense. We reprinted the boards and are trying it on the "top" bank of cameras. The bridge cameras seem to be a good idea, and may be something to look into after adjusting camera angels/zoom to get the same board cameras seen by the inner four cameras at the same time. We have been thinking of either reprinting a very large board (perhaps 4'x6x') to make this task feasible. Is there a good source where we can read into the specifics of calibration?

**Comment by DestroytheCity** [comment]
Update: we were able to get a solid 3D pose estimation using four cameras and a massive CharUco board, however, the skeleton still seems to be displaced relative from myself and the CharUco board seems to be showing up in test runs. Any ideas @mprib @jonmatthis @aaroncherian? We have been using a saved calibration (see the google drive bottom bank calibration) and then replacing synced videos. Thanks in advance for all your help! Really cool stuff
