### ISSUE TITLE
Marking and detecting arm gestures

### ISSUE THREAD

**Issue by abitrolly** [freemocap/freemocap#26]
Is is possible to teach the system to recognize certain arm gestures? I am looking to create slide switcher that can run on single web camera and so far I haven't seen solutions that let to mark continous, but finite movement to make AI/NN learn it and infer events.

**Comment by jonmatthis** [comment]
I think you could probably do that with MediaPipe! What you are describing is pretty far from our standard use case, but our framework can probably be hacked apart to get you in a good position to work on what you want. 

Especially if you just want to work with one camera, it wouldn't be too much work to configure freemocap to open a webcam and run MediaPipe on it while outputting an estimate of hand/arm position in close-to-realtime. 

If you are interesting in pursuing more, you could fork a branch of the repo and we can try to help you configure things for your purposes!


@aaroncherian

**Comment by jonmatthis** [comment]
that might also be overkill though! You could also just go check out MediaPipe and see if their webcam demos are enough for what you need (e.g. https://google.github.io/mediapipe/solutions/holistic.html)

**Comment by abitrolly** [comment]
@jonmatthis I actually talked to MediaPipe guys maybe two years ago and they were busy optimizing the code to be run on mobile devices. I still do not see "action learning and recognition" examples there, so adding a branch for experimenting sounds like a good start. If the code depends only on points and their historical position, it might turn up to be portable between MediaPipe and FreeMoCap.

As I see what needs to be done.

1. Interface for marking actions

As a user I want to place a start marker on the dataset when I begin gesture, and end mark when I end the action. I might use space button, but if all my limbs are busy, an alternative signal such as voice command or a wireless/wired controller should also be possible. For that, video processing should be synchronized with audio recording and event recording stream.

2. Feeding the marked gesture data to different models to train them.

Documenting what are inputs/outputs of each model, what are processing requirements, getting results for comparison. Experimenting with methods to preprocess the video to get better results in insufficient light conditions or when the person is too close/too far away (normalizing distance).

3. Running the gesture recognition on a RaspberryPI with web cam and training it for switching slides in 5 minutes or less.

**Comment by jonmatthis** [comment]
This all seems doable! I could see this being helpful for people working in more clinical settings too, as folks in those communities regularly need to tag behaviors for later analysis.

Just to be clear - are you talking about marking gestures and whatnot at run time (i.e. while you're recording the video) or after the fact (i.e. while watching through prerecorded videos)?

Both are doable, I'm just curious about your vision for this feature

**Comment by abitrolly** [comment]
@jonmatthis ideally I am looking for run-time marking and teaching. Maybe with an ability to rewind and review later. That creates a feedback loop with a human inside for "online machine learning", which is where I want to put myself. If I am preparing the presentation, I may have all my hands busy for editing and marking video, but with run time tagging I could make the whole process with just a single button.

**Comment by jonmatthis** [comment]
Hey! 

One of the developers of anipose just popped up in the server to say that they're adding a visualizer with behavioral marking functionality - https://discord.com/channels/760487252379041812/867173338958790706/869270956605071420 (let me know if you can't access this link) 

Would this be helpful for your needs?
