### ISSUE TITLE
How to Use Saved Calibration?

### ISSUE THREAD

**Issue by ArcticFox31** [freemocap/freemocap#268]
How do I use a saved calibration for new videos? Ie. calibrated it with boards, now want to perform a test?

**Comment by aaroncherian** [comment]
The readme will be of help here:
https://github.com/freemocap/freemocap/blob/main/OLD_README.md

the `use_saved_calibration` flag is set to `False` by default. When `False`, FreeMoCap will automatically store the calibration data from the last successful session that you ran. So when you have calibration you want to use, i.e. you've run a set of videos with that calibration through at least stage 3 of FreeMoCap (it doesn't need to run through Stage 4 onwards, though you can if you want to) - for the next set of recordings that you want to do, you can set the flag to `use_saved_calibration = True`.  While this is `True`, every subsequent session that gets run through FreeMoCap will use that last saved calibration.

**Comment by ArcticFox31** [comment]
Ah. So I need to create a new folder (using previously recorded videos), then set use_saved_calibration to true? No need to copy over the calibration.toml or any data array folders from calibration run to the test run folder?

**Comment by aaroncherian** [comment]
hmm - let me know if this step-by-step procedure matches what you did!

1) Run FreeMoCap on the calibration session, and have `use_saved_calibration = False`, and run it through at least Stage 3 
2) Run FreeMoCap on another session with your videos in them, and have `use_saved_calibration=True`

The sessions have to be run consecutively for the saved calibration to work properly. 

Also, make sure that you're using the latest pre-alpha version (0.0.54, https://github.com/freemocap/freemocap/releases/tag/v0.0.54).

**Comment by aaroncherian** [comment]
hey! can you elaborate on that? 

Is it throwing up an error somewhere?

**Comment by ArcticFox31** [comment]
Hi! No errors, everything runs perfectly. The only thing we notice are the same CharUco dots that are generated in the calibration in our next run that goes off that same calibration. For context, we are running calibration using CharUco boards with use_saved_calibration = False, then creating a new folder and running it with use_saved_calibration = True. We are using external cameras, so in both cases we are dropping videos into t
<img width="682" alt="Screen Shot 2022-11-11 at 11 30 21 AM" src="https://user-images.githubusercontent.com/117693803/201416606-3dd970de-d7a0-41e0-93f4-899972a69ed0.png">
he SyncedVideo folder (all videos already have same number of frames).
