### ISSUE TITLE
FMC on Greyscale Videos

### ISSUE THREAD

**Issue by DestroytheCity** [freemocap/freemocap#269]
Hello! We are running into an issue in which FMC seems to be swapping the skeletons generated from one camera onto the view of another camera (see video). Is this a potential result of using greyscale cameras? The calibration seems to work fine as the video generated reflects accurate skeletons, just placed on the wrong camera (ie camera 1 generates skeleton 1, but skeleton 1 is placed onto the view of camera 3). Has anyone encountered similar issues/have any suggestions on how to resolve this issue? Thank you in advance!

https://user-images.githubusercontent.com/114196168/201419033-18be83ad-e852-4a82-b116-9fbfe470bec2.mp4

**Comment by DestroytheCity** [comment]
Hey thanks for the response! We're calibrating on just four cameras (confirmed with the ...camera_calibration.toml). 

Trying to install the alpha GUI right now, but we're getting an error "Module Not Found Error: No module named src." 

Can we run the alpha in a terminal window instead?

**Comment by DestroytheCity** [comment]
Hey thanks for the response! There are only 4 cameras in the camera_calibration.toml. 

After we upload the synced videos to the alpha gui, how do we begin calibration? We created a new session and see the uploaded videos.

**Comment by jonmatthis** [comment]
ohh, think I know what's happening!

Looking at the Drive folder from the other Issue - https://drive.google.com/drive/folders/1wv4RHzPFDLeIXr9xONC72fhbW3MKQT_q?usp=sharing

...I see that you've altered the folder names and alot of the sessions are just called `sesh` - I think that's messing up something in the calibration system and causing it to load the wrong files at some point in the process. 

I think the easiest thing for you now is to re-process the videos from these recordings  with the `alpha` GUI - it's not *totally* fully tested yet, but hopefully it will help you move forward with your project. 

Give me a moment to write up a quick `How-To` guide on a workflow you can use to re-process your existing videos

**Comment by DestroytheCity** [comment]
Makes a lot of sense! Thank you so much for doing that. All of our videos are pre-recorded (using external cameras) that are already synced.

**Comment by jonmatthis** [comment]
Ok - Give this a shot and let me know how it goes!

https://freemocap.readthedocs.io/en/latest/How_to_Guides/how_to_process_previously_recorded_videos/

**Comment by DestroytheCity** [comment]
Wow @jonmatthis working perfectly. Still working out some kinks w/blender but the output is amazing. In awe right now 🥲

**Comment by jonmatthis** [comment]
Thank you so much for this comment and your work/interest in this project!

And come join the discord, if you like :D
