### ISSUE TITLE
Alpha GUI - No module cv2 aruco

### ISSUE THREAD

**Issue by klich3** [freemocap/freemocap#285]
Hi there,

After activate Conda env and after install all requirements I found with next message
`No module cv2 "aruco"`

To solve this its needed uinstall opencv and install again with contribution pack with next commands:

`
pip3 uninstall opencv-python
pip3 uninstall opencv-contrib-python
pip3 install opencv-contrib-python
`

Regards

**Comment by jonmatthis** [comment]
Oh whoops! We recently removed a dependency that I now realize was installing `opencv-contrib-python` for us, so we need to specify it explicitly. 

Give me a sec to double-check the version we want and I'll fix this soon. 

Thanks for the heads up!

**Comment by jonmatthis** [comment]
Ok, I've added `opencv-contrib-python==4.6.0.66` to the `requirements.txt` file. 

Thanks again!

**Comment by klich3** [comment]
Thanks :)
Regards
