### ISSUE TITLE
Convert npy to csv for openpose 3Ddata

### ISSUE THREAD

**Issue by danialldev** [freemocap/freemocap#290]
Hi,
Is there any code for converting openPoseSkel_3d.npy to a csv file?

**Comment by trentwirth** [comment]
Hey there!

there isn't specific code that we've written, but it isn't difficult

I'd recommend you try it yourself first, this link is a good place to start

https://www.geeksforgeeks.org/convert-a-numpy-array-into-a-csv-file/

___

Give it a shot and if you need help I'd be more than happy to write a script that'll take care of it to you. Also, just for a frame of reference, if you could let me know which version of FreeMoCap you're using that would help me give you assistance if you need it!

**Comment by trentwirth** [comment]
I'll write you up a script that will take care of this for you, I'll get it to you by Tuesday of next week!

**Comment by danialldev** [comment]
> I'll write you up a script that will take care of this for you, I'll get it to you by Tuesday of next week!

Thank you very much. I will be waiting.

**Comment by trentwirth** [comment]
@danialldev, I just want to let you know that I'm still working on this - is there a specific `openPoseSkel_3d.npy` file that you're trying to convert? I've got one from demo data that Jon had, but we haven't generated openpose in a while and I want to make sure that what I'm working on will solve your issue

**Comment by danialldev** [comment]
> 

Hey there,
Have there been any updates?

**Comment by trentwirth** [comment]
@danialldev I asked a question last week - if you let me know what openpose data you're working with I can proceed!

**Comment by danialldev** [comment]
> @danialldev I asked a question last week - if you let me know what openpose data you're working with I can proceed!

I am using freemocap 0.0.54, I believe `openPoseSkel_3d.npy` have the same data arrangement in all runs and versions. you can download my openpose output files using any of the following links:

[https://app.blackhole.run/#SfdwZXqu1Y1HqVKvNMupjnqMZLgf9Wu9KX6wxF3JxX9J](url)

[https://file.io/olx6OAspr9cH](url)

**Comment by danialldev** [comment]
> @danialldev, I just want to let you know that I'm still working on this - is there a specific `openPoseSkel_3d.npy` file that you're trying to convert? I've got one from demo data that Jon had, but we haven't generated openpose in a while and I want to make sure that what I'm working on will solve your issue

Hey there,
Have there been any updates?
can I have the code that you already wrote?

**Comment by danialldev** [comment]
> @danialldev I asked a question last week - if you let me know what openpose data you're working with I can proceed!

Follow up? @trentwirth

**Comment by danialldev** [comment]
> https://file.io/olx6OAspr9cH

Follow up? @trentwirth

**Comment by trentwirth** [comment]
hi @danialldev - sorry that this fell off of my radar, we've been focusing on an update. I've just downloaded your files, I'll take a look later this afternoon and give you a time estimate for when I'll have it complete.

**Comment by trentwirth** [comment]
Hi @danialldev , I've worked out a solution in a jupyter notebook and have it put up on my Google Drive via Colab. 

[here's a link to the script](https://drive.google.com/file/d/12bLZsiCWlyNBJGzOczHWOrS9tm6zWmyL/view?usp=sharing)

Good luck!

**Comment by danialldev** [comment]
> Hi @danialldev , I've worked out a solution in a jupyter notebook and have it put up on my Google Drive via Colab.
> 
> [here's a link to the script](https://drive.google.com/file/d/12bLZsiCWlyNBJGzOczHWOrS9tm6zWmyL/view?usp=sharing)
> 
> Good luck!

@trentwirth  Thank you for providing the code. Unfortunately, it doesn't solve the problem I'm facing. The generated CSV file doesn't have column names that represent the landmark names on the body. I need a CSV file that is similar to the one generated for MediaPipe, where each column has a landmark name that represents a specific landmark on the body.

Do you have any suggestions on how I can modify the code to achieve this requirement? I would greatly appreciate any help you can provide.

Thank you again for your time and effort in helping me with this.
