### ISSUE TITLE
License of Outputed Animations is AGPL, or End User Owned?

### ISSUE THREAD

**Issue by Hunanbean** [freemocap/freemocap#319]
It is unclear if the Output of the Capture is owned by the user or is under the AGPL.
Simply put, are the animations mine, or must i release/share them under the AGPL?

Thank you

p.s. Specifically when using MediaPipe as i will not use OpenPose

**Comment by KaijuKoder** [comment]
It would be good to clarify this. 



The Github license says ACADEMIC OR NON-PROFIT ORGANIZATION NONCOMMERCIAL RESEARCH USE ONLY. There appears to be a commercial license available too, but it's expensive.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/LICENSE
https://cmu.flintbox.com/technologies/b820c21d-8443-4aa2-a49f-8919d93a8740
https://news.ycombinator.com/item?id=23367560

**Comment by KaijuKoder** [comment]
MediaPipe seems to have an Apache license, which from this exchange allows commercial use: https://github.com/google/mediapipe/issues/1290#issuecomment-727150276

Freemocap has an AGPL license. I couldn't find a clear answer, though this from GNU about the GPL might answer your question: : https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput

The OpenPose license has a Github license says ACADEMIC OR NON-PROFIT ORGANIZATION NONCOMMERCIAL RESEARCH USE ONLY. There appears to be a commercial license available too, but from these links it's expensive and doesn't permit use for sports.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/LICENSE
https://cmu.flintbox.com/technologies/b820c21d-8443-4aa2-a49f-8919d93a8740
https://news.ycombinator.com/item?id=23367560

**Comment by Hunanbean** [comment]
Great, thank you! it Seems from that information that i would 'own' the
output from Mediapipe + Freemocap, but not from OpenPose (which i will
avoid using)
I will move forward with that thought. I would be great if a lawyer could
double verify for us too.

**Comment by KaijuKoder** [comment]
Unfortunately no lawyer will verify that without being written a check, but I think your understanding is right.

Agree OpenPose is best avoided. Not really "Open".

**Comment by philipqueen** [comment]
Hi, great question! You own the data you produce with FreeMoCap and you own the animations you create with that data.

The AGPL applies to the software, not what is made with the software. As you point out, OpenPose is different and more restricted in your allowed uses.
