### ISSUE TITLE
Integrate post-processing widget

### ISSUE THREAD

**Issue by aaroncherian** [freemocap/freemocap#386]

**Comment by philipqueen** [comment]
Options are replacing the Data viewer tab with the post-processing widget, or just adding a tab for post processing. I'll start by making a new tab and we'll consider replacing the data viewer later.

Aaron's widget is [here](https://github.com/aaroncherian/postprocessing_gui) and a fork is [here](https://github.com/freemocap/postprocessing_gui). Aaron will eventually have it on pip.

**Comment by trentwirth** [comment]
overlaps with skellyforge
