### ISSUE TITLE
Consider MediaPipe for full body pose estimation

### ISSUE THREAD

**Issue by MohamedAliRashad** [freemocap/freemocap#39]
openpose is a good solution but it's development is discontinued, [Mediapipe](https://google.github.io/mediapipe/solutions/holistic) on the other hand is developed by Google and has a simple to use guide with very robust trackers.

**Comment by aaroncherian** [comment]
yup - mediapipe integration into the pipeline is something that we're currently working on.

**Comment by MohamedAliRashad** [comment]
@aaroncherian I was planning to make a blender addon using it in a separate repo. if you would like i can help you develop the addon here.
