### ISSUE TITLE
Quality of Life - We need a way to exclude a video from the processing pipeline

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#41]
like, if Camera 2 can't detect the charuco board, we should be able to set a flag to ignore that video so we can still reconstruc the sesh from the remaining videos. 

Currently, I'm trying to do that manually and it keeps dropping errors due to things expecting to find things shaped appropriately for the original  number of cameras

**Comment by aaroncherian** [comment]
worth mentioning that with this, we'd also have to make sure the skipped video gets noted down so that in future reconstructions, that video is not used if you're starting from a later stage.
