### ISSUE TITLE
PyApp - Single-click installer

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#415]
Need to develop some way to install and run freemocap without the command-line

**Comment by trentwirth** [comment]
- Endurance and Reyes are on board to help out with this! Woo!

**Comment by trentwirth** [comment]
- will work on this in freemocap server! Trent pick a time :D

**Comment by trentwirth** [comment]
potential issues:
- skellyforge import
- hidden imports not found
- matplotlib backend
- ctypes dlls

we'll see how many of these errors/warnings are fixed by correcting skellyforge import

**Comment by trentwirth** [comment]
a bunch of imports were relative, they're being switched to absolute (in skellyforge)

next steps: someone keeps fixing the little bugs in pyinstaller that come from trying to create the executable.

pyinstaller should work on the OS's that we run it on:
- [ ] mac
- [ ] windows
- [ ] linux

This will eventually be a github actions thing :)

**Comment by trentwirth** [comment]
Currently crashing on newer macs -- 
- [ ] @trentwirth , try running pyinstaller on M2 machine and see if I can get the application to not crash on record
- [ ] ready to try on Windows and Linux

**Comment by philipqueen** [comment]
Linux app for testing: https://github.com/freemocap/freemocap/actions/runs/6461298266
Windows app for testing: https://github.com/freemocap/freemocap/actions/runs/6461298263

Linux app has not been tested.
Windows app opens, but hasn't been fully tested.
Intel Mac is not currently running, need to pair with someone with an intel mac to make sure it will work.
Need another person to test on sonoma/m2 mac for the arm mac version

**Comment by trentwirth** [comment]
Jon tested on windows and directory view is super laggy - probably needs to be refactored

**Comment by trentwirth** [comment]
Philip has new downloads for everyone to try! Let's do it ✅

**Comment by trentwirth** [comment]
Test PyApp install on:

## Linux:
- [ ] install
- [ ] single cam recording
- [ ] multi-cam recording

## Mac:
- [ ] install
- [ ] single cam recording
- [ ] multi-cam recording

## Windows:
- [ ] install
- [ ] single cam recording
- [ ] multi-cam recording

**Comment by jonmatthis** [comment]
After looking at all the great info @philipqueen put on the actual PR #514 - I realized that we should probably move towards putting as much of the discussion related to these various tasks on the PR itself (rather than popping up Issues for each task, as we have been) 

@trentwirth

**Comment by trentwirth** [comment]
Next step: retest pyapps across platforms
- [ ] mac intel
- [ ] mac silicon/arm
- [ ] windows
- [ ] linux

**Comment by trentwirth** [comment]
runs on Linux with "Kitchen Sink" install

```bash
sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
```

Trent & Jon need to run installs on their macs :)

**Comment by jonmatthis** [comment]
Getting breaking security errors on Win 11 - going to push and just say "it doesn't work on Windows 11"
