### ISSUE TITLE
improve post-processing pipeline

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#426]
improve default post-processing piepline

Including something to orient relative to gravity

**Comment by jonmatthis** [comment]
#431

**Comment by trentwirth** [comment]
- skellyforge; external package, integrated into the pipeline
- post-processing pipeline runs on internal guts of skellyforge
- big next step: figure out a GUI aspect -- integrate into current GUI or make a separate one? <- Jon: leave this off for now, eventually have a pop-up window

**Comment by jonmatthis** [comment]
WE achieved the main goal here, which was to improve our post processing pipeline

further work will require refactoring various things at various levels, but we can call this good for now. 

--

Nothing blocking moving forward on this, but we might need/want to refactor the structure of this pipeline

we can refactor the `process_recording_folder` part of the `freemocap` software in preparation for a bigger refactor after the 1.0 release. 

- need to figure out whether/how we can do any refactor at this level that will be helpful to the actual issues with integrating `skellyforge` more directly into the standard `freemocap` pipelines/gui/etc

The smaller scale refactor can be a test of the patterns and architecture we might want to pull into the the 2.0 structure 


---
