### ISSUE TITLE
Blender executable can't be found nor selected on linux

### ISSUE THREAD

**Issue by chrbinder** [freemocap/freemocap#428]
Whenever I'm running freemocap (1.0.13rc0), the last step of the process fails as the blender file path cannot be set.
When I'm manually browsing to find the file in `/usr/bin/`, the file dialog shows a lot of executable files but not blender. I've checked with another browser that the file is indeed there.
Blender is also in my path. When selecting the desktop entry, freemocap accepts the file path but crashes on clicking `Export to Blender`:

`[2023-06-15 17:42:43.0673] [    INFO] [freemocap.export_data.blender_stuff.call_blender_subprocess_methods] [call_blender_subprocess_megascript_take2():160] [PID:28933 TID:140113568896832] Starting `blender` sub-process with this command: 
 ['/home/chbinder/Schreibtisch/blender.desktop', '--background', '--python', '/home/chbinder/.local/lib/python3.11/site-packages/freemocap/export_data/blender_stuff/blender_bpy_export_scripts/freemocap_blender_megascript_take2.py', '--', '/home/chbinder/freemocap_data/recording_sessions/session_2023-06-15_16_54_53/recording_16_55_08_gmt+2', '/home/chbinder/freemocap_data/recording_sessions/session_2023-06-15_16_54_53/recording_16_55_08_gmt+2/recording_16_55_08_gmt+2.blend']
Traceback (most recent call last):
  File "/home/chbinder/.local/lib/python3.11/site-packages/freemocap/gui/qt/main_window/freemocap_main_window.py", line 324, in _export_active_recording_to_blender
    export_to_blender(
  File "/home/chbinder/.local/lib/python3.11/site-packages/freemocap/export_data/blender_stuff/export_to_blender.py", line 29, in export_to_blender
    call_blender_subprocess_megascript_take2(
  File "/home/chbinder/.local/lib/python3.11/site-packages/freemocap/export_data/blender_stuff/call_blender_subprocess_methods.py", line 162, in call_blender_subprocess_megascript_take2
    blender_process = subprocess.Popen(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Keine Berechtigung: '/home/chbinder/Schreibtisch/blender.desktop'
`

**Comment by philipqueen** [comment]
Hi @chrbinder, sorry for the delay in responding. I'm not a linux user, and I'm not very familiar with application paths in Linux. That being said, we'd certainly like to support Linux in the automated pathfinding for Blender.

From doing a little research, it seems like the problem you're encountering is because you're pointing freemocap to the blender desktop shortcut, which contains the app itself but also some other information. You'll want to point freemocap directly to the app, which blender says should be found inside of `$HOME/.config/blender/3.5/` or `/usr/share/blender/3.5/`.

If you run `which blender`, what prints out?

**Comment by chrbinder** [comment]
Hi @philipqueen, thanks a lot!
When entering `which blender`, it shows `/usr/bin/blender`.
I've tried the desktop shortcut because the blender executable is not listed when manually trying to set the path from within freemocap. When I navigate to `/usr/bin` with the freemocap file dialog, all the other executables are shown but not blender. I can, however, start blender perfectly fine from a terminal window by entering `/usr/bin/blender`.

**Comment by philipqueen** [comment]
Thanks @chrbinder! I've made a pull request that tries to find the blender executable where you described, and in similar locations: [check it out here](https://github.com/freemocap/freemocap/pull/442). If you'd like to try it out to see if it works, you can run `pip uninstall freemocap` followed by `pip install https://github.com/freemocap/freemocap/archive/philip/find-linux-executable.zip` (assuming you pip installed freemocap. If you cloned it instead you can checkout the branch from the PR).

This assumes the file you have the path for is an executable, which is a good bet. But if the solution above doesn't work I'll keep troubleshooting it.

**Comment by chrbinder** [comment]
Hi, thanks for the update!

Now, the blender executable gets detected by freemocap, yay!

It was, however, still not possible to launch blender directly through the GUI and freemocap logged this:


```
Blender quit
Blender returned an error:

[2023-07-08 11:02:38.0078] [    INFO] [freemocap.data_layer.export_data.blender_stuff.call_blender_subprocess_methods] [call_blender_subprocess_megascript_take2():173] [PID:6339 TID:139698301491008] Done with blender stuff :D
[2023-07-08 11:02:38.0079] [    INFO] [freemocap.data_layer.export_data.blender_stuff.export_to_blender] [export_to_blender():47] [PID:6339 TID:139698301491008] blender subprocess finished
QObject::moveToThread: Current thread (0x5558c43241f0) is not the object's thread (0x5558c45affe0).
Cannot move to target thread (0x5558c43241f0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/chbinder/freemocap/lib/python3.11/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.
```

By following advice from [here](https://github.com/NVlabs/instant-ngp/discussions/300#discussioncomment-3179213) I manually uninstalled opencv-contrib-python and installed opencv-python-headless and now everything works!

Btw, before manually enabling "rigify" in blender, it would show an additional error that rigify could not be found.

Thanks again for you patch, I'm excited to try it out! :)

**Comment by philipqueen** [comment]
I looked into this error a bit - We'll have to test more to make sure opencv-python-headless is a fully working replacement for opencv-contrib-python, but it's great to know its a patch for now.
