### ISSUE TITLE
Synchronized Videos not being found in active recording widget after importing

### ISSUE THREAD

**Issue by philipqueen** [freemocap/freemocap#444]
The active recording widget is listing "Synchronized Videos Recorded" as false, despite showing 2 synchronized videos in the console. This prevents me from being able to calibrate from the videos, as the calibrate from videos button is linked to the active recording status. Processing the videos through mediapipe has no issues though.

<img width="1424" alt="Screen Shot 2023-07-05 at 4 36 54 PM" src="https://github.com/freemocap/freemocap/assets/24758117/50b3bee7-9f89-412c-89d8-34c298f3374f">

**Comment by aaroncherian** [comment]
Hey! So I checked on a couple of different sessions, and the `Synchronized Videos Recorded` check worked properly for me!

**Comment by philipqueen** [comment]
Yeah I'm guessing this was a session specific error, I'll close it for now.
