### ISSUE TITLE
Charuco board link in tutorial needs to be updated

### ISSUE THREAD

**Issue by aaroncherian** [freemocap/freemocap#448]
The link to the Charuco board here (https://freemocap.readthedocs.io/en/latest/getting_started/multi_camera_calibration/#multi-camera-calibration-guide) doesn't work, probably because the location of the charuco png got shuffled around. 

I also think the runme/main page should link to the charuco board as well.

**Comment by philipqueen** [comment]
I made a PR to fix the link. I think either moving the link to the guides on single camera and calibration from the bottom of the page to the top, or duplicating them in a tooltip box could help too

**Comment by philipqueen** [comment]
Just pushed the PR fixing this in the docs repo
