### ISSUE TITLE
Batch processing expects an output data folder to exist

### ISSUE THREAD

**Issue by aaroncherian** [freemocap/freemocap#462]
So I was trying to use the batch processing code, and I ran into this error:

`Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'D:\\2023-07-26_SBT002\\1.0_recordings\\calib_1\\sesh_2023-07-26_14_19_10_STB002_NIH_Trial1\\output_data\\recording_parameters.json'
  File "C:\Users\aaron\Documents\GitHub\freemocap\experimental\batch_process\batch_process.py", line 65, in process_recording_without_gui
    save_dictionary_to_json(
  File "C:\Users\aaron\Documents\GitHub\freemocap\experimental\batch_process\batch_process.py", line 40, in process_folder_of_session_folders
    process_recording_without_gui(
  File "C:\Users\aaron\Documents\GitHub\freemocap\experimental\batch_process\batch_process.py", line 92, in <module>
    process_folder_of_session_folders(
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\2023-07-26_SBT002\\1.0_recordings\\calib_1\\sesh_2023-07-26_14_19_10_STB002_NIH_Trial1\\output_data\\recording_parameters.json'`

This happens in the `save_dictionary_to_json` function in `batch_process.py`. As far as I understand, the function is trying to save the `json` into the `output_data` folder, but that folder doesn't exist yet, so we get this error.

This file used to work fine, so my guess is that there's a recent update that caused this to stop working. I've done a manual workaround to create an `output_data` folder in each session, and that works fine, but we should still try and make a fix for it, even if its just adding a pathlib line to create the `output_data` folder.

**Comment by philipqueen** [comment]
Made a PR to fix this, but we may want to change the way we handle this folder creation - discussed in the PR if you have input
