### ISSUE TITLE
Improve documentation for error "qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found."

### ISSUE THREAD

**Issue by calamitywithinsanity** [freemocap/freemocap#484]
For reference, my computer is running **Ubuntu 20.04.6 LTS.**

When following the installation tutorial, I encountered the following error message after attempting to launch the GUI using the "freemocap" command:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, offscreen, vnc, minimal, eglfs, xcb, wayland, linuxfb, minimalegl, vkkhrdisplay.

Aborted (core dumped)
```

After some searching, I was able to **solve** this issue for myself:

The error occurred on when I was attempting to launch the GUI (the last step on the Installation tutorial)

1. I entered the following command into the terminal at the same location that I was trying to run the "freemocap" command.

```
export QT_DEBUG_PLUGINS=1
```
2. I retried the "freemocap" command and received a large text output. In this output, I was able to see the following section where "xcb" is mentioned (this is a partial copy/paste):

```
qt.core.plugin.factoryloader: looking at "/home/calamity/anaconda3/envs/freemocap-env/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /home/calamity/anaconda3/envs/freemocap-env/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
```

3. Given that this output said 

```
looking at "/home/calamity/anaconda3/envs/freemocap-env/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so
```

I ran the following command:

```
ldd /home/calamity/anaconda3/envs/freemocap-env/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so | grep "not found"
```

This led to the following output:
```
	libxcb-cursor.so.0 => not found
	libxcb-cursor.so.0 => not found
```

4. Seeing that libxcb-cursor.so.0 was missing, I installed the missing library. Note: the missing library is called "libxcb-cursor0" so the following command worked:

```
sudo apt install libxcb-cursor0
```
5. After running the "freemocap" command again, the GUI was able to launch.

-----

**Good references that helped me solve this problem (these posts are not directly related to freemocap but they were encountering similar issues)**

----
https://askubuntu.com/questions/1271976/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found
**Archive link:** https://web.archive.org/web/20230324140844/https://askubuntu.com/questions/1271976/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found

This post gave me the knowledge of doing the "export QT_DEBUG_PLUGINS=1" command, the "ldd /home/calamity/anaconda3/envs/freemocap-env/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so | grep "not found"" command and the knowledge that I needed to install some missing packages.

----
https://askubuntu.com/questions/1471030/how-to-install-the-libxcb-cursor-so-0-library
**Archive link:** https://web.archive.org/web/20230924042031/https://askubuntu.com/questions/1471030/how-to-install-the-libxcb-cursor-so-0-library

This post gave me the knowledge that the actual library is "libxcb-cursor0" (I was trying to do "sudo apt-get install libxcb-cursor.so.0" which failed)

Hope this helps :) <3

**Comment by philipqueen** [comment]
Hi @calamitywithinsanity, I hope this helps some other Linux users. I haven't seen this exact problem before though. Maybe at some point a "Linux Troubleshooting" documentation is in order. I'm going to mark this as closed, as we have a planned documentation overhaul on the way

**Comment by SmoothBrainApe** [comment]
You're my hero! Just encountered this issue! worked like a charm
