### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by gvs** [freemocap/freemocap#495]
After executing the freemocap command, it gets stuck on the last line and always stops here. Still the same after multiple restarts. I have correctly installed the skelly_synchronize library.
The operation is as follows:

Setting up freemocap logging  C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\freemocap\system\logging\configure_logging.py
[2023-11-06 17:09:07.0129] [    INFO] [freemocap] [<module>():19] [PID:40688 TID:40252] Initializing freemocap package, version: v1.0.23-rc, from file: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\freemocap\__init__.py
Thank you for using skelly_viewer!
This is printing from: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skelly_viewer\__init__.py
Source code for this package is available at: https://github.com/freemocap/skelly_viewer/
adding base_package_path: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skelly_viewer : to sys.path
[2023-11-06 17:09:07.0848] [   DEBUG] [matplotlib] [wrapper():324] [PID:40688 TID:40252] matplotlib data path: D:\Program Files\Python310\lib\site-packages\matplotlib\mpl-data
[2023-11-06 17:09:07.0858] [   DEBUG] [matplotlib] [wrapper():324] [PID:40688 TID:40252] CONFIGDIR=C:\Users\GPSON\.matplotlib
[2023-11-06 17:09:07.0860] [   DEBUG] [matplotlib] [<module>():1492] [PID:40688 TID:40252] interactive is False
[2023-11-06 17:09:07.0861] [   DEBUG] [matplotlib] [<module>():1493] [PID:40688 TID:40252] platform is win32
[2023-11-06 17:09:07.0900] [   DEBUG] [matplotlib] [wrapper():324] [PID:40688 TID:40252] CACHEDIR=C:\Users\GPSON\.matplotlib
[2023-11-06 17:09:07.0903] [   DEBUG] [matplotlib.font_manager] [_load_fontmanager():1540] [PID:40688 TID:40252] Using fontManager instance from C:\Users\GPSON\.matplotlib\fontlist-v330.json
[2023-11-06 17:09:08.0285] [    INFO] [skelly_viewer.config.logging_configuration] [configure_logging():43] [PID:40688 TID:40252] Logging already configured!
adding base_package_path: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skellycam : to sys.path
Setting up skellycam logging C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skellycam\system\log_config\logsetup.py
[2023-11-06 17:09:08.0293] [    INFO] [skellycam.system.log_config.logsetup] [configure_logging():42] [PID:40688 TID:40252] Logging already configured!
[2023-11-06 17:09:08.0293] [    INFO] [skellycam] [<module>():27] [PID:40688 TID:40252] Initializing skellycam package, version: v2023.09.1086, from file: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skellycam\__init__.py
[2023-11-06 17:09:08.0551] [   DEBUG] [h5py._conv] [<module>():47] [PID:40688 TID:40252] Creating converter from 7 to 5
[2023-11-06 17:09:08.0551] [   DEBUG] [h5py._conv] [<module>():47] [PID:40688 TID:40252] Creating converter from 5 to 7
[2023-11-06 17:09:08.0552] [   DEBUG] [h5py._conv] [<module>():47] [PID:40688 TID:40252] Creating converter from 7 to 5
[2023-11-06 17:09:08.0552] [   DEBUG] [h5py._conv] [<module>():47] [PID:40688 TID:40252] Creating converter from 5 to 7
Thank you for using skellyforge!
This is printing from: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skellyforge\__init__.py
Source code for this package is available at: https://github.com/freemocap/skellyforge/
Thank you for using skelly_synchronize!
This is printing from: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skelly_synchronize\__init__.py
Source code for this package is available at: https://github.com/freemocap/skelly_synchronize/
adding base_package_path: C:\Users\GPSON\AppData\Roaming\Python\Python310\site-packages\skelly_synchronize : to sys.path

**Comment by gvs** [comment]
when i install this package:



C:\Windows\system32>pip install setuptools
Requirement already satisfied: setuptools in d:\program files\python310\lib\site-packages (65.5.0)

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Windows\system32>pip install Cython
Requirement already satisfied: Cython in d:\program files\python310\lib\site-packages (0.29.35)

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Windows\system32>pip install numpy
Requirement already satisfied: numpy in d:\program files\python310\lib\site-packages (1.23.5)

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Windows\system32>pip install freemocap
Collecting freemocap
  Using cached freemocap-0.0.54-py3-none-any.whl (237 kB)
Collecting matplotlib~=3.1.3
  Downloading matplotlib-3.1.3.tar.gz (40.9 MB)
     ---------------------------------------- 40.9/40.9 MB 11.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting freemocap
  Using cached freemocap-0.0.53-py3-none-any.whl (234 kB)
  Using cached freemocap-0.0.52-py3-none-any.whl (214 kB)
  Using cached freemocap-0.0.51-py3-none-any.whl (184 kB)
  Using cached freemocap-0.0.50-py3-none-any.whl (176 kB)
Collecting moviepy~=1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ruamel.yaml>=0.15.0 in d:\program files\python310\lib\site-packages (from freemocap) (0.17.28)
Collecting typed-ast<1.5,>=1.4.0
  Using cached typed_ast-1.4.3.tar.gz (210 kB)
  Preparing metadata (setup.py) ... done
Collecting pydantic==1.9.0
  Downloading pydantic-1.9.0-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 19.2 MB/s eta 0:00:00
Collecting rich~=10.4.0
  Using cached rich-10.4.0-py3-none-any.whl (206 kB)
Requirement already satisfied: aniposelib==0.4.3 in c:\users\gpson\appdata\roaming\python\python310\site-packages (from freemocap) (0.4.3)
Collecting pyudev==0.22.0
  Downloading pyudev-0.22.0.tar.gz (85 kB)
     ---------------------------------------- 85.1/85.1 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: h5py>=3.1.0 in d:\program files\python310\lib\site-packages (from freemocap) (3.8.0)
Collecting gunicorn==20.1.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting aiomultiprocess==0.9.0
  Using cached aiomultiprocess-0.9.0-py3-none-any.whl (17 kB)
Collecting numpy<=1.19
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      performance hint: _common.pyx:275:19: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:299:19: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:322:50: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:426:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:465:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:509:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:592:36: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:596:36: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:600:36: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:604:36: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:638:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:675:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:712:63: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:754:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:785:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:903:40: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:907:40: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:911:41: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:916:40: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:920:41: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:924:38: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:960:31: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:1002:32: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _generator.pyx:706:41: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: _generator.pyx:735:45: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i

              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------

      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Traceback (most recent call last):
        File "C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py", line 235, in <module>
          main()
        File "C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "C:\Users\GPSON\AppData\Local\Temp\pip-install-a8jvqd8c\numpy_18069700e23e4b4bae42791468b8504a\tools\cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "D:\Program Files\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:\\Program Files\\Python310\\python.exe', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\GPSON\AppData\Local\Temp\pip-build-env-bbl2pxld\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\GPSON\AppData\Local\Temp\pip-build-env-bbl2pxld\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\GPSON\AppData\Local\Temp\pip-build-env-bbl2pxld\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 274, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by philipqueen** [comment]
Hi @gvs, I have seen that `h5py` library logging before, and it's generally associated with an environment issue.

Try making a new conda (or virtual env) environment and then run `pip install --pre freemocap` in that environment and see if running freemocap works there.

**Comment by gvs** [comment]
> Hi @gvs, I have seen that `h5py` library logging before, and it's generally associated with an environment issue.
> 
> Try making a new conda (or virtual env) environment and then run `pip install --pre freemocap` in that environment and see if running freemocap works there.
> 
> EDIT: It looks like pip was trying to install an old version. We've pushed 1.0 now, so running `pip install freemocap --upgrade` should fix your issue

Thank you!

According to your method, it can now run. Thank you!
