### ISSUE TITLE
Status is false，why？

### ISSUE THREAD

**Issue by RebeccaDD** [freemocap/freemocap#517]
Why Status is False？
<img width="1280" alt="image" src="https://github.com/freemocap/freemocap/assets/154681024/9da3b75f-5986-424a-99f2-4bfcd7dc6588">

**Comment by ajc27-git** [comment]
That is because in that capture session you haven't processed the videos or the processing failed before getting any 2D data. That's the same status as just importing or recording videos.

**Comment by philipqueen** [comment]
Yep, as you process those should turn to True as each step in the pipeline succeeds. If you run the pipeline and there's still False values there, then you can tell where the process failed
