### ISSUE TITLE
Charuco board parameters should be in documentation

### ISSUE THREAD

**Issue by brayevalerien** [freemocap/freemocap#542]
The documentation does not provide the set of parameters used to generate the charuco board. Apparently it is important, since freemocap did not find the board in my calibration videos.
![image](https://github.com/freemocap/freemocap/assets/60972074/3957caf4-d38b-4a6b-943e-a159812fb670)
Website: [calib.io](https://calib.io/pages/camera-calibration-pattern-generator)

**Comment by philipqueen** [comment]
Hi @brayevalerien,

You can find our charuco definition here:
https://github.com/freemocap/freemocap/blob/main/freemocap/core_processes/capture_volume_calibration/charuco_stuff/charuco_board_definition.py

I don't see an immediate difference between the charuco boards, unless its in the checker width, or if calib.io's DICT_4X4 doesn't match the DICT_4X4_250 from opencv we use. We do highly recommend just using the charuco board images here to print, as its hard to verify if external services will perfectly match the board we use: https://github.com/freemocap/freemocap/tree/main/freemocap/assets/charuco 

That being said, I'll go ahead and add the charuco defintion to our calibration troubleshooting here: https://freemocap.github.io/documentation/calibration-troubleshooting.html
