### ISSUE TITLE
Fix the "million multiprocesses" thing that happens when processing folders

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#547]
Spawning a process is a costly thing, we should only spawn the ones we need. 

(Also, we need to take those dumb print statements out of the `__init__` files for the relevant repos - if they go anywhere, they should be in the `__main__.py` entry point, so they on hit once

![Image](https://github.com/freemocap/freemocap/assets/15314521/76a07f15-d255-487c-9309-fb4a2ddea7fc)

**Comment by philipqueen** [comment]
Are you using the most recent build? Skellytracker is now only spinning up one process per video, and the pyproject.toml was only updated to reflect that recently. Unless we're spinning up these processes elsewhere, which I don't think we're using many. 

Agreed on removing print statements though
