### ISSUE TITLE
Annotated Images fail to produce when `YOLO crop` is turned on

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#548]

**Comment by philipqueen** [comment]
@jonmatthis I just tested this on the sample data and annotated videos are created. Did something go wrong in the processing step?

**Comment by jonmatthis** [comment]
@philipqueen - Yep, it does work - I was confused because the filesize in the GUI didn't update (and I think i was looking at an aborted run that made invalid videos, so the combo of those two made me think it was broken) 

![image](https://github.com/freemocap/freemocap/assets/15314521/cc4fc409-18f7-4516-b6ee-3cb66dbcdb1b)
