### ISSUE TITLE
Detect Blender installation automatically

### ISSUE THREAD

**Issue by PaulForest** [freemocap/freemocap#580]
# Issue: The install location of Blender is not set initially, so when we export data, calls to Blender fail.

Every time FreeMoCap opens, the value for "Blender Executable Path" in the "Export Settings" tab is set to "None".

# Steps to reproduce

1. If you have previously downloaded the test data, delete or rename the directory: C:\Users\USERNAME\freemocap_data\recording_sessions\freemocap_sample_data so this looks like a fresh start
2. Start FreeMoCap
3. Load up the sample data via the menu "Data/Download Sample Data (3 Cameras, ~1000 frames)". 
4. Wait for the files to load up by watching the console for progress.
5. Click "Process Data" tab
6. Select "Calibrate from Active Recording"
7. Set the "Charuco square size (mm)" to 58.0
8. Click "Run calibration..."
9. Wait for the progress to finsh by watching the console for progress.  
10. Click "Process Motion Capture Videos" (still under "Process Data" tab)
11. Wait for the progress to finsh by watching the console for progress.  
12. An error is logged at this point with a line similar to:
`[2024-04-27T09:10:51.0044][ERROR ] [ProcessID: 22184, ThreadID: 23404] [freemocap.gui.qt.main_window.freemocap_main_window:_handle_export_to_blender_finished():322] ::: Blender file does not exist! Did something go wrong in the `export_to_blender` call above?.`

# Symptoms:

Here's the log output: 

[FreeMoCap-BlenderNotFound.txt](https://github.com/freemocap/freemocap/files/15138386/FreeMoCap-BlenderNotFound.txt)

# Workaround

1. Before clicking "Process Motion Capture Videos" (under "Process Data" tab), change to the "Export Data" tab
2. Click "Choose your Blender Executable" and use the file picker to find your Blender executable (ex: C:/Program Files/Blender Foundation/Blender 4.1/blender.exe)
3. Change to the "Process Data" tab and click "Process Motion Capture Videos"
4. Wait for the progress to finsh by watching the console for progress.
5. Process finishes correctly!  Blender opens up the generated .blend file and it looks great.  

# Potential Solutions

Blender's executable should probably be detected automatically, as most users will have one Blender install. 

If more than one Blender install is detected, we should somehow communicate to the user that they need to pick one, and we should remember their selection from the last session.  This seems like a less-likely scenario.  

I'm not a Python guy but maybe this could do it:
https://stackoverflow.com/questions/55394905/how-to-find-the-location-of-an-executable-in-python

# Notes

In Blender, you also need to have "Rigging: Rigify" plugin enabled.  
However, even if you do, the steps to reproduce above will still get the error.

**Comment by philipqueen** [comment]
Hi @PaulForest, thanks for a very thorough issue report! 

We do make an attempt to find the Blender path, you can see the implementation here: https://github.com/freemocap/freemocap/blob/main/freemocap/core_processes/export_data/blender_stuff/get_best_guess_of_blender_path.py
If your path is at `C:/Program Files/Blender Foundation/Blender 4.1/blender.exe` it should be finding it well. Is that where your Blender executable is but isn't being found?

I also have an active PR #562 that will remember the user chosen Blender path across sessions, which will alleviate the pain of not having Blender found automatically. 

Hopefully we can make the automatic Blender path finding better though.

**Comment by philipqueen** [comment]
We just merged in the functionality of remembering the blender executable between sessions, so you should be able to manually set it once and have it be remembered. Just upgrade to 1.2.0 with `pip install freemocap --upgrade`.

I'm going to close the issue, but would still be interested to hear where your blender executable is so we can make sure it's found automatically in a future update.
