### ISSUE TITLE
Start up fails on empty drives

### ISSUE THREAD

**Issue by brknsoul** [freemocap/freemocap#581]
It seems that freemocap (or rather `get_best_guess_of_blender_path.py`) doesn't know how to deal with empty drives, such as optical drives.

I had a user that had an empty blu-ray drive (F:) and `get_best_guess_of_blender_path.py` kept failing while trying to search that drive for `F:\Program Files\Blender Foundation`.

Problem solved by removing F from the list of drives to check.

Attached console log.
[New_Text_Document_6.txt](https://github.com/freemocap/freemocap/files/15142178/New_Text_Document_6.txt)

**Comment by philipqueen** [comment]
Thanks for the issue! 

I've made a PR that patches this. In the event of the error message above it will just continue gracefully instead of failing. Thanks again!
