### ISSUE TITLE
VR potential

### ISSUE THREAD

**Issue by DonFlymoor** [freemocap/freemocap#60]
This is an amazing peice of software for inexpensive mocap. Are there any plans for using it with VR? This would be great for realtime body tracking, hand tracking, and object tracking for a very low cost, if integrated with steamVR with virtual trackers.

**Comment by MajorFox-MJ** [comment]
Hello there,
You should keep that in the [discussion tab](https://github.com/freemocap/freemocap/discussions) instead of creating an issue.
(Make sure to remove this issue after that)

**Comment by monsieurpooh** [comment]
There is no discussion tab and the link is dead. What was the result of the discussion? Does anyone have an updated link?
