### ISSUE TITLE
(Feature Request) Choosing needed keypoints instead of including them all in motion capture

### ISSUE THREAD

**Issue by AmirHoseinMazrooei** [freemocap/freemocap#610]
First, thank you for this amazing software.

I think many people won’t need the face keypoints for motion capture, or they might need specific parts for motion capture. For example, I just need the hand and fingers of the right hand for motion capture (I am doing some analysis on kinematic movement for my master’s thesis).

Having an option for including or excluding different parts of the body would give more freedom in using the software and make it faster for some people's needs.

**Comment by philipqueen** [comment]
Hi @AmirHoseinMazrooei, thanks for the feedback! We're in the process of generalizing our code to work with other pose estimation models right now (#592). As part of that, we'll be able to include all of the sub models from mediapipe separately (body only, hands only, face only).
