### ISSUE TITLE
Exe installer not working?

### ISSUE THREAD

**Issue by Felina-Lain** [freemocap/freemocap#614]
Hi, I wanted to give this program a try but I'm awful at using python and commands lines, so I was super happy to see an exe existed, even if experimental and thought I'd try it.

I did see written that the install process run hidden in background so it can look like nothing is happening even if it is installing, so after launching the exe I waited around 2h, then figured that it probably was done by then?

But there was no new executable for me to use. So I tried re-clicking the installer to see if something new happened, and nothing.
It flashes a cmd window for a brief moment, but no gui, no app... am I missing a step?

I'm using the FreeMoCap 1.2.0 exe on a windows 10 laptop

**Comment by philipqueen** [comment]
Hi @Felina-Lain,

I'm sorry to hear you're having trouble with our exe. We're having another user on the Discord server reporting problems with the windows executable right now, so it's possible its broken.

Two things you can try while we test on our end are:
1) Go into the windows security settings, and make sure the executable isn't being blocked by Windows permissions
2) Try deleting the downloaded executable and redownloading

```
Deleting your FreeMoCap download

To delete a version of FreeMoCap downloaded through an installer, you must delete both the executable/app file, and the PyApp file found in the path below. You can either delete the entire freemocap folder, or specific versions inside the folder.
Platform 	Path
macOS 	~/Library/Application Support/pyapp
Windows 	%USERPROFILE%\AppData\Local\pyapp
Unix 	$XDG_DATA_HOME/pyapp (the [XDG_DATA_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) environment variable default is ~/.local/share)
```

**Comment by Felina-Lain** [comment]
> Hi @Felina-Lain,
> 
> I'm sorry to hear you're having trouble with our exe. We're having another user on the Discord server reporting problems with the windows executable right now, so it's possible its broken.
> 
> Two things you can try while we test on our end are:
> 
> 1. Go into the windows security settings, and make sure the executable isn't being blocked by Windows permissions
> 2. Try deleting the downloaded executable and redownloading
> 
> ```
> Deleting your FreeMoCap download
> 
> To delete a version of FreeMoCap downloaded through an installer, you must delete both the executable/app file, and the PyApp file found in the path below. You can either delete the entire freemocap folder, or specific versions inside the folder.
> Platform 	Path
> macOS 	~/Library/Application Support/pyapp
> Windows 	%USERPROFILE%\AppData\Local\pyapp
> Unix 	$XDG_DATA_HOME/pyapp (the [XDG_DATA_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) environment variable default is ~/.local/share)
> ```

Hi, I did both, but same thing (I didn't wait 2 h this time, just 20 min)
So, eventually I decided to try the python with pip, and I was worried I'd mess up, but I did manage to get it to open!
So, not a solution or anything, exe still not working, but the software is XD

**Comment by philipqueen** [comment]
I'm glad you got it working!

I took the time to fix the installers, so they should be working now: https://github.com/freemocap/freemocap/releases/tag/v1.2.0
