### ISSUE TITLE
Questions about 3D joint depth

### ISSUE THREAD

**Issue by lllluy** [freemocap/freemocap#641]
Hi author,

Thank you for your work.
I found that the 3D joints visualized by the GUI seemed to have no depth, as shown in the figure below, when I lifted my right leg, the front view of the 3D view seemed to be visually correct, however, when I looked at it from the top view, it seemed that all the joints were in one plane, i.e. there was no difference in depth. What is the reason for this?

![企业微信截图_17273175562704](https://github.com/user-attachments/assets/34c06355-2970-46a4-acaf-cb44c13e963d)
![2](https://github.com/user-attachments/assets/46589404-8e9e-44b1-96d7-928e2f6fcdb7)

**Comment by philipqueen** [comment]
Hello, it appears you're using a single camera for capture. We support single camera capture primarily for testing and getting familiar with the software. We encourage users to transition to multiple cameras to get 3D reconstructions, as multiple views are required for reliable 3d data.

That being said, we do allow 3d data form 2d captures if you enable it in the settings. You can uncheck the checkbox shown in the image below and get 3d data out. Be warned the quality might be lower than you expect. If it doesn't suit your needs, try adding a camera or two for good 3d capture.

![Flatten 2D data? checkbox](https://github.com/user-attachments/assets/172d37b6-9401-445a-a258-3d9c45fd26cb)
