### ISSUE TITLE
More detailed Spine

### ISSUE THREAD

**Issue by kledo-34** [freemocap/freemocap#645]
I would like to use the mocap to analyze acrobatic movement with OpenSim, however the spine is only one segment and therefore not very detailed when it comes to back bends and other acrobatic movement, is there a possibility to add a more detailed spine (e.g. with more segments) or do you know a workaround for me to get this spine data included or to extend the ai that recognizes the joints.

Apart from that, thank you very much for this awsome Software.

**Comment by philipqueen** [comment]
Hello @kledo-34,

We're actively working on extending freemocap to work with other pose estimation models, which would allow us to add a model that has more detailed tracking of the spine. For now however, the only option is mediapipe.

If you are aware of another pose estimation model that has the level of detail in the spine that you would like, please let us know and we can evaluate including that as an option. Otherwise, it is likely that DeepLabCut (DLC) will be an option, and that would allow you to train a model with the level of spine detail you desire.

**Comment by kledo-34** [comment]
Hey @philipqueen,
thank you very much for your fast and great answer. I actually don't know a model with a detailed spine estimation, but your suggestion to use DLC is great, I tested this and it should definitely work, especially because I can import labeled data created by the mediapipe option and then only have to add and adjust the additional spine points.
I am very happy that it is planned to integrate this into the software. Since I am currently in a planning stage for my project and I also need to prepare some other aspects to make it work, I would like to ask without pressure and stress if there is a rough time estimate until when it will be possible to use DLC in freemocap and mybe you could keep me informed here ;)

Thank you very much for your work on this great project!!!

**Comment by philipqueen** [comment]
Great, I'm glad Mediapipe+DLC is able to get you where you need! I'm going to close this issue, but feel free to ask more questions if you have them.

As far as timeline goes, we have already done most of the work generalizing the backend. The remaining work is on the visualization side, both for simple plots and for the blender output. By the end of the year I think it would be very possible for us to have a guide on running DLC models through freemocap *with some manual work* and get a simple plotted animation out. I think getting it into Blender will take longer than that, as will getting a polished DLC + freemocap integration. 

To be more clear about the manual work, it would look something like this: Process videos through 2d tracking in freemocap to get original mediapipe data -> process separately through DLC to get extra spine points -> edit a `.py` script to tell freemocap how to handle your extra data -> process through freemocap from the script. You can see the existing YOLO and OpenPose examples of this in the `experimental` folder in freemocap. We could probably work on making an `.ipynb` that would walk through the steps.

**Comment by kledo-34** [comment]
Very cool, thank you very much, I'm looking forward to this :)

Actually I think I can run the whole body 2d tracking through DLC, I just thought that I would generate the first initial training data for DLC with mediapipe as creating training data is very time consuming.
My manual work would then only be run 2d tracking with the DLC model and then run it with freemocap to get the 3d data. As I need to manually adjust the 3d data anyways to get it into open sim, I actually only need the raw data, I don't need a blender conversion etc. so that's no problem.

Thank you very much for answering and for your work, I really appreciate that 👍
