### ISSUE TITLE
 run the program on external recordings

### ISSUE THREAD

**Issue by hadi1376tm** [freemocap/freemocap#78]
Hi, i like to know how to run the program on my own external recordings.

**Comment by aaroncherian** [comment]
Hi, in the next few weeks we'll be pushing out a new update that will make running external recordings possible. Just to prepare though, on your end feeding external recordings in it is important to make sure that all the videos are time-synced and have the same number of frames. We've been using the audio-sync capabilities of video editing software to sync and edit our videos to achieve that.

**Comment by hadi1376tm** [comment]
> Hi, in the next few weeks we'll be pushing out a new update that will make running external recordings possible. Just to prepare though, on your end feeding external recordings in it is important to make sure that all the videos are time-synced and have the same number of frames. We've been using the audio-sync capabilities of video editing software to sync and edit our videos to achieve that.

Hi, thanks, so we should provide synced videos, what video editing software do you suggest to sync and edit videos?

**Comment by abitrolly** [comment]
Also, is it possible to detect when videos are out of sync and have different frame rate?
