### ISSUE TITLE
live demo

### ISSUE THREAD

**Issue by faheuer** [freemocap/freemocap#80]
Is it possible to create live pose predictions with this repository with video input streamed directly from the cameras? If not, do you think your pipeline is fast enough (regarding the networks used on say, a RTX 2080) to tweak it and make it run live at a somewhat decent framerate?

**Comment by aaroncherian** [comment]
just to clarify, do you mean in terms of 2D pose or 3D reconstructions? If it comes to 2D pose tracking, in our next update we do have an option to run previews of the cameras simultaneously while tracking using mediapipe, which might be close to what you're looking at. With a 2080 I'd think you'd be at least able to run 3 webcams at once, at lowest resolution (640x480) using that method at a decent framerate. That being said, that was developed specifically just to help a person position themselves before running a recording, so it might not be as robust as what you're looking for just yet and you might run into crashes if it exceeds what your computer/card can handle.

If you mean pose predictions in terms of 3D reconstructions, @jonmatthis would like to develop/has been working on a method for real-time 3D reconstruction, so it is on the to-do list for the future.
