### ISSUE TITLE
Unable to utilize Blender file conversion

### ISSUE THREAD

**Issue by Shirtsy** [freemocap/freemocap#91]
When I try to process my FMC data through stage 5, after selecting my Blender.exe location, I am presented with the following error before the software skips to the next stage and processes the data into a video.

```
CompletedProcess(args=['C:/Users/bru5/OneDrive/Shared
Materials/Art/Blender/Blender_Launcher/Builds/stable/blender-2.93.7+lts.a5b7f9dc9011/blender.exe', '--background', '--python',
'C:\\Users\\bru5\\miniconda3\\envs\\freemocap-env\\lib\\site-packages\\freemocap\\fmc_blender.py', '--',
'C:\\Users\\bru5\\FreeMocap_Data\\sesh_2022-01-14_20_58_58\\DataArrays\\mediaPipeSkel_3d.npy',
'C:\\Users\\bru5\\FreeMocap_Data\\sesh_2022-01-14_20_58_58\\DataArrays'], returncode=0, stdout="Blender 2.93.7 (hash a5b7f9dc9011 built
2021-12-15 00:40:08)\nRead prefs: C:\\Users\\bru5\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.93\\config\\userpref.blend\nWarning: 'BlendyPose' does not contain '_PT_' with prefix and
suffix\nregister_class(...):\nWarning: 'BlendyPose' does not contain '_PT_' with prefix and suffix\n\nBlender quit\n",
stderr='C:\\Users\\bru5\\miniconda3\\envs\\freemocap-env\\lib\\site-packages\\freemocap\\fmc_blender.py:134: SyntaxWarning: "is" with a
literal. Did you mean "=="?\n  if(v_relationship[index] is "weight"):\nTraceback (most recent call last):\n  File "<string>", line 1,
in <module>\n  File "C:\\Users\\bru5\\miniconda3\\envs\\freemocap-env\\lib\\site-packages\\freemocap\\fmc_blender.py", line 24, in
<module>\n    markers_list = np.load(build_data)\n  File "C:\\Users\\bru5\\OneDrive\\Shared Materials\\Art\\Blender\\Blender_Launcher\\
Builds\\stable\\blender-2.93.7+lts.a5b7f9dc9011\\2.93\\python\\lib\\site-packages\\numpy\\lib\\npyio.py", line 416, in load\n    fid =
stack.enter_context(open(os_fspath(file), "rb"))\nFileNotFoundError: [Errno 2] No such file or directory:
\'C:\\\\Users\\\\bru5\\\\miniconda3\\\\envs\\\\freemocap-env\\\\Lib\\\\site-packages\\\\freemocap\\\\build_data.npy\'\n')
```

**Comment by aaroncherian** [comment]
@jonmatthis

**Comment by Shirtsy** [comment]
I put the file where you specified and received the exact same error message after selecting my Blender install location.

**Comment by Norsninja** [comment]
Hi, I feel I have an issue that might be similar. When I get to the Blender process, I receive this error before it skips to the next stage like the other user experienced. No .blend file is produced. Thank you

`Blender 3.1.2 (hash cc66d1020c3b built 2022-03-31 23:39:57)
Read prefs: C:\Users\Name M Name\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
Error: Cannot read file 'C:\Users\Name N Name\C': No such file or directory
Exception in module register(): E:\SteamLibrary\steamapps\common\Blender\3.1\scripts\addons\amaranth\__init__.py
====================
Bradley's Geo Node Presets
====================
Reloading external rigs...
Reloading external metarigs...
The custom presets directory seems invalid: /Remap Presets/

Blender quit`

**Comment by jonmatthis** [comment]
thanks @Norsninja! 

@Shirtsy - Are you still having this issue? Maybe this solution could help?
